
*preparemerge.do
clear
use ../data/working/productfile_consumption_ids


ge product=""

replace product="COFFEE SHORT" if item_description=="COFFEE SHORT"
replace product="COFFEE TALL" if item_description=="COFFEE TALL"
replace product="COFFEE GRANDE" if item_description=="COFFEE GRANDE"
replace product="MILK TALL" if item_description=="MILK KIDS"
replace product="APPLE JUICE SHORT" if item_description=="APPLE JUICE KIDS"
replace product="HOT CHOCOLATE SHORT" if item_description=="COCOA KIDS"
replace product="MILK TALL" if item_description=="MILK STEAMED TALL"
replace product="MILK GRANDE" if item_description=="MILK STEAMED GRANDE"
replace product="ESPRESSO SOLO" if item_description=="ESPRESSO SINGLE"
replace product="ESPRESSO SOLO" if item_description=="ESPRESSO DOUBLE"
replace product="BAGEL PLAIN" if item_description=="BAGEL WITH CREAM CHEESE"
replace product="ESPRESSO MACCHIATO SOLO" if item_description=="ESPRESSO MACCHIATO SINGLE"
replace product="ESPRESSO MACCHIATO DOPPIO" if item_description=="ESPRESSO MACCHIATO DOUBLE"
replace product="CREAM CHEESE" if item_description=="CREAM CHEESE"
replace product="ESPRESSO CON PANNA SOLO" if item_description=="ESPRESSO CON PANNA SINGLE"
replace product="ESPRESSO CON PANNA DOPPIO" if item_description=="ESPRESSO CON PANNA DOUBLE"
replace product="TEA SHORT" if item_description=="TEA SHORT"
replace product="TEA TALL" if item_description=="TEA TALL"
replace product="TEA GRANDE" if item_description=="TEA GRANDE"
replace product="CAPPUCCINO SHORT" if item_description=="CAPPUCCINO SHORT"
replace product="CAPPUCCINO TALL" if item_description=="CAPPUCCINO TALL"
replace product="CAPPUCCINO GRANDE" if item_description=="CAPPUCCINO GRANDE"
replace product="CAFFE LATTE SHORT" if item_description=="LATTE SHORT"
replace product="CAFFE LATTE TALL" if item_description=="LATTE TALL"
replace product="CAFFE LATTE GRANDE" if item_description=="LATTE GRANDE"
replace product="TAZO BLACK SHAKEN ICED TEA TALL" if item_description=="TEA ICED REFILL"
replace product="CAFFE MOCHA SHORT" if item_description=="MOCHA SHORT"
replace product="CAFFE MOCHA TALL" if item_description=="MOCHA TALL"
replace product="CAFFE MOCHA GRANDE" if item_description=="MOCHA GRANDE"
replace product="MILK SHORT" if item_description=="MILK STEAMED SHORT"
replace product="MILK" if item_description=="MILK"
replace product="MILK TALL" if item_description=="MILK SMALL"
replace product="ESPRESSO SHOT" if item_description=="ESPRESSO SHOT"
replace product="APPLE JUICE SHORT" if item_description=="APPLE JUICE SHORT"
replace product="APPLE JUICE TALL" if item_description=="APPLE JUICE TALL"
replace product="APPLE JUICE GRANDE" if item_description=="APPLE JUICE GRANDE"
replace product="SCONE MAPLE OAT NUT" if item_description=="SCONE MAPLE"
replace product="COFFEE TALL" if item_description=="DRIP REFILL TALL"
replace product="CAFFE MISTO/CAFE AU LAIT SHORT" if item_description=="MISTO SHORT"
replace product="CAFFE MISTO/CAFE AU LAIT TALL" if item_description=="MISTO TALL"
replace product="CAFFE MISTO/CAFE AU LAIT GRANDE" if item_description=="MISTO GRANDE"
replace product="CAFFE AMERICANO SHORT" if item_description=="AMERICANO SHORT"
replace product="CAFFE AMERICANO TALL" if item_description=="AMERICANO TALL"
replace product="CAFFE AMERICANO GRANDE" if item_description=="AMERICANO GRANDE"
replace product="" if item_description=="FRAPPUCCINO MOCHA 4 PACK"
replace product="MUFFIN BLUEBERRY" if item_description=="MUFFIN BLUEBERRY"
replace product="MUFFIN LEMON POPPYSEED" if item_description=="MUFFIN LEMON"
replace product="SCONE MAPLE OAT NUT" if item_description=="SCONE OAT"
replace product="ROLL CINNAMON" if item_description=="SWEETROLL CINNAMON ROLL"
replace product="ROLL MULTIGRAIN" if item_description=="BREAD MULTIGRAIN ROLL"
replace product="CAKE CLASSIC COFFEE" if item_description=="CAKE CLASSIC COFFEE"
replace product="COOKIE CHOCOLATE CHIP" if item_description=="COOKIE CHOCOLATE CHIP"
replace product="COOKIE PEANUT BUTTER" if item_description=="COOKIE PEANUT BUTTER"
replace product="COOKIE MOLASSES" if item_description=="COOKIE MOLASSES"
replace product="COOKIE SNICKERDOODLE" if item_description=="COOKIE SNICKERDOODLE"
replace product="CROISSANT BUTTER" if item_description=="CROISSANT BUTTER"
replace product="DANISH CHEESE" if item_description=="SWEETROLL DANISH CREAM CHEESE"
replace product="MUFFIN PUMPKIN CREAM CHEESE" if item_description=="MUFFIN PUMPKIN"
replace product="COOKIE WHITE CHOCOLATE CRANBERRY" if item_description=="COOKIE WHITE CHOCOLATE"
replace product="SCONE BLUEBERRY" if item_description=="SCONE BLUEBERRY"
replace product="MUFFIN APPLE BRAN" if item_description=="MUFFIN BRAN"
replace product="SCONE LEMON POPPYSEED" if item_description=="SCONE LEMON"
replace product="CROISSANT CHOCOLATE" if item_description=="CROISSANT CHOCOLATE"
replace product="CAKE BANANA NUT LOAF" if item_description=="CAKE BANANA LOAF"
replace product="CAKE BANANA NUT LOAF" if item_description=="CAKE ZUCCHINI LOAF"
replace product="ROLL CINNAMON" if item_description=="SWEETROLL CINNAMON TWIST"
replace product="TART RUSTIC APPLE" if item_description=="TART APPLE"
replace product="ICED COFFEE TALL" if item_description=="SHAKEN ICED COFFEE SHORT"
replace product="ICED COFFEE TALL" if item_description=="SHAKEN ICED COFFEE TALL"
replace product="ICED COFFEE GRANDE" if item_description=="SHAKEN ICED COFFEE GRANDE"
replace product="" if item_description=="DRIP 1 GALLON"
replace product="" if item_description=="DRIP 2.5 GALLON"
replace product="" if item_description=="DRIP 5 GALLON"
replace product="" if item_description=="FILTERS #4 PK/100"
replace product="EGGNOG LATTE TALL" if item_description=="EGGNOG LATTE TALL"
replace product="NONFAT MILK TALL" if item_description=="MILK NON-FAT"
replace product="BREVE" if item_description=="BREVE"
replace product="WHIP CREAM" if item_description=="WHIP CREAM"
replace product="LIGHT FLAVORED SYRUP" if item_description=="LIGHT VANILLA SYRUP"
replace product="LIGHT FLAVORED SYRUP" if item_description=="LIGHT ALMOND SYRUP"
replace product="LIGHT FLAVORED SYRUP" if item_description=="LIGHT HAZELNUT SYRUP"
replace product="FLAVORED SYRUP" if item_description=="VANILLA SYRUP"
replace product="FLAVORED SYRUP" if item_description=="ALMOND SYRUP"
replace product="FLAVORED SYRUP" if item_description=="HAZELNUT SYRUP"
replace product="FLAVORED SYRUP" if item_description=="SHOT VANILLA SYRUP"
replace product="FLAVORED SYRUP" if item_description=="SHOT HAZELNUT SYRUP"
replace product="FLAVORED SYRUP" if item_description=="SHOT ALMOND SYRUP"
replace product="COOKIE SNICKERDOODLE" if item_description=="COOKIE SEASONAL"
replace product="BAGEL PLAIN" if item_description=="BAGEL PLAIN"
replace product="SCONE RASPBERRY" if item_description=="SCONE RASPBERRY"
replace product="CAKE LEMON LOAF" if item_description=="CAKE LEMON LOAF"
replace product="COFFEE FRAPPUCCINO BLENDED COFFEE GRANDE" if item_description=="FRAPPUCCINO COFFEE GRANDE"
replace product="MOCHA FRAPPUCCINO BLENDED COFFEE GRANDE" if item_description=="FRAPPUCCINO MOCHA GRANDE"
replace product="ICED CAFFE AMERICANO TALL" if item_description=="AMERICANO ICED TALL"
replace product="ICED CAFFE AMERICANO GRANDE" if item_description=="AMERICANO ICED GRANDE"
replace product="ICED CAFFE MOCHA TALL" if item_description=="MOCHA ICED TALL"
replace product="ICED CAFFE MOCHA GRANDE" if item_description=="MOCHA ICED GRANDE"
replace product="ICED CAFFE LATTE TALL" if item_description=="LATTE ICED TALL"
replace product="ICED CAFFE LATTE GRANDE" if item_description=="LATTE ICED GRANDE"
replace product="CLAW BEAR WITH ALMONDS" if item_description=="SWEETROLL BEAR CLAW DANISH"
replace product="" if item_description=="PRESSED COFFEE 8CUP"
replace product="SOY MILK" if item_description=="ADD SOY MILK"
replace product="ESPRESSO FRAPPUCCINO BLENDED COFFEE TALL" if item_description=="FRAPPUCCINO COFFEE TALL"
replace product="MOCHA FRAPPUCCINO BLENDED COFFEE TALL" if item_description=="FRAPPUCCINO MOCHA TALL"
replace product="STEAMED APPLE JUICE SHORT" if item_description=="STEAM APPLE SHORT"
replace product="STEAMED APPLE JUICE TALL" if item_description=="STEAM APPLE TALL"
replace product="STEAMED APPLE JUICE GRANDE" if item_description=="STEAM APPLE GRANDE"
replace product="CAKE CRUMBLE COFFEE" if item_description=="CAKE CRUMBLE COFFEE"
replace product="TART RUSTIC APPLE" if item_description=="TART FRUIT"
replace product="PACK BLACK AND WHITE COOKIE - 2" if item_description=="COOKIE BLACK & WHITE"
replace product="COFFEE SHORT" if item_description=="DRIP REFILL SHORT"
replace product="COFFEE GRANDE" if item_description=="DRIP REFILL GRANDE"
replace product="MUFFIN LOWFAT CRANBERRY" if item_description=="MUFFIN LOWFAT CRANBERRY"
replace product="SANDWICH LOWFAT TUNA" if item_description=="SANDWICH TUNA"
replace product="SANDWICH TUSCAN VEGETABLE" if item_description=="SANDWICH ROAST VEGETABLE"
replace product="SALAD TUNA CORE" if item_description=="SALAD TUNA CORE"
replace product="SALAD FRUIT" if item_description=="FRUIT SALAD"
replace product="" if item_description=="DRIP AIRPOT"
replace product="COFFEE VENTI" if item_description=="COFFEE VENTI"
replace product="CAFFE LATTE VENTI" if item_description=="LATTE VENTI"
replace product="CAFFE MOCHA VENTI" if item_description=="MOCHA VENTI"
replace product="CAFFE MISTO/CAFE AU LAIT VENTI" if item_description=="MISTO VENTI"
replace product="CAFFE AMERICANO VENTI" if item_description=="AMERICANO VENTI"
replace product="TEA VENTI" if item_description=="TEA VENTI"
replace product="CAPPUCCINO VENTI" if item_description=="CAPPUCCINO VENTI"
replace product="MILK VENTI" if item_description=="MILK VENTI"
replace product="ESPRESSO TRIPLE" if item_description=="ESPRESSO TRIPLE"
replace product="ESPRESSO QUADRUPLE" if item_description=="ESPRESSO QUADRUPLE"
replace product="ESPRESSO MACCHIATO TRIPLE" if item_description=="ESPRESSO MACCHIATO TRIPLE"
replace product="ESPRESSO MACCHIATO QUADRUPLE" if item_description=="ESPRESSO MACCHIATO QUADRUPLE"
replace product="ESPRESSO CON PANNA TRIPLE" if item_description=="ESPRESSO CON PANNA TRIPLE"
replace product="ESPRESSO CON PANNA QUADRUPLE" if item_description=="ESPRESSO CON PANNA QUADRUPLE"
replace product="STEAMED APPLE JUICE VENTI" if item_description=="STEAM APPLE VENTI"
replace product="ESPRESSO FRAPPUCCINO BLENDED COFFEE TALL" if item_description=="ESPRESSO FRAPPUCCINO TALL"
replace product="ESPRESSO FRAPPUCCINO BLENDED COFFEE GRANDE" if item_description=="ESPRESSO FRAPPUCCINO GRANDE"
replace product="BAGEL CINNAMON RAISIN" if item_description=="BAGEL CINNAMON RAISIN"
replace product="SQUARE CRISPY" if item_description=="BAR CRISPY SQUARE"
replace product="CARAMEL MACCHIATO SHORT" if item_description=="CARAMEL MACCHIATO SHORT"
replace product="CARAMEL MACCHIATO TALL" if item_description=="CARAMEL MACCHIATO TALL"
replace product="CARAMEL MACCHIATO GRANDE" if item_description=="CARAMEL MACCHIATO GRANDE"
replace product="CARAMEL MACCHIATO VENTI" if item_description=="CARAMEL MACCHIATO VENTI"
replace product="COOKIE RAINBOW" if item_description=="COOKIE M & M"
replace product="FRITTER TOP POT APPLE" if item_description=="DOUGHNUT APPLE FRITTER"
replace product="BAGEL SESAME" if item_description=="BAGEL SESAME"
replace product="LOAF PUMPKIN" if item_description=="CAKE PUMPKIN LOAF"
replace product="ROLL CINNAMON" if item_description=="SWEETROLL PECAN ROLL"
replace product="MUFFIN LOWFAT CHOCOLATE" if item_description=="MUFFIN LOWFAT CHOCOLATE"
replace product="BAR BROWNIE WITH NUTS" if item_description=="BAR CHOCOLATE BROWNIE"
replace product="COOKIE GINGER CHEW" if item_description=="COOKIE GINGER"
replace product="SCONE LOWFAT OAT FRUIT" if item_description=="SCONE LOWFAT OAT"
replace product="BREAD CHEESE TWIST" if item_description=="BREAD CHEESE TWIST"
replace product="BAGEL MULTIGRAIN" if item_description=="BAGEL MULTIGRAIN"
replace product="HOT CHOCOLATE SHORT" if item_description=="HOT CHOCOLATE SHORT"
replace product="HOT CHOCOLATE TALL" if item_description=="HOT CHOCOLATE TALL"
replace product="HOT CHOCOLATE GRANDE" if item_description=="HOT CHOCOLATE GRANDE"
replace product="HOT CHOCOLATE VENTI" if item_description=="HOT CHOCOLATE VENTI"
replace product="COOKIE DOUBLE CHOCOLATE BROWNIE" if item_description=="COOKIE TRIPLE CHOCOLATE"
replace product="SANDWICH EGG SALAD" if item_description=="SANDWICH EGG SALAD CORE"
replace product="" if item_description=="ESPRESSO BARISTA STAINLESS"
replace product="SCONE LOWFAT CRANBERRY" if item_description=="SCONE LOWFAT CRANBERRY"
replace product="SALAD HARVEST" if item_description=="SALAD HARVEST"
replace product="BAR CARAMEL TOFFEE ALMOND" if item_description=="BAR ALMOND TOFFEE"
replace product="CUPCAKE BLACK BOTTOM" if item_description=="CUPCAKE BLACK BOTTOM"
replace product="" if item_description=="FRUIT AND CHEESE WINTER CORE"
replace product="CAKE LEMON LOAF" if item_description=="CAKE LEMON POUND"
replace product="" if item_description=="MIX, COOKIE GINGERBREAD BEAR"
replace product="" if item_description=="DCF SUMATRA 8OZ WB FL CAN"
replace product="CAKE MARBLE LOAF" if item_description=="CAKE MARBLE LOAF"
replace product="TAZO CHAI TEA LATTE SHORT" if item_description=="CHAI LATTE SHORT"
replace product="TAZO CHAI TEA LATTE TALL" if item_description=="CHAI LATTE TALL"
replace product="TAZO CHAI TEA LATTE GRANDE" if item_description=="CHAI LATTE GRANDE"
replace product="TAZO CHAI TEA LATTE VENTI" if item_description=="CHAI LATTE VENTI"
replace product="TAZO CHAI ICED TEA LATTE TALL" if item_description=="CHAI LATTE ICED TALL"
replace product="TAZO CHAI ICED TEA LATTE GRANDE" if item_description=="CHAI LATTE ICED GRANDE"
replace product="FLAVORED SYRUP" if item_description=="SHOT SF VANILLA SYRUP"
replace product="BAGEL ASIAGO CHEESE" if item_description=="BAGEL CHEESE"
replace product="DANISH CHEESE" if item_description=="SWEETROLL CHEESE DANISH"
replace product="" if item_description=="CHOCO FOILED HEARTS (9 PIECE)"
replace product="COFFEE SHORT" if item_description=="COFFEE SHORT"
replace product="COFFEE TALL" if item_description=="COFFEE TALL"
replace product="COFFEE GRANDE" if item_description=="COFFEE GRANDE"
replace product="COFFEE VENTI" if item_description=="COFFEE VENTI"
replace product="SCONE PUMPKIN" if item_description=="SCONE PUMPKIN"
replace product="DOUGHNUT TOP POT CLASSIC GLAZED OLD FASHIONED" if item_description=="DOUGHNUT GLAZED"
replace product="COFFEE VENTI" if item_description=="DRIP REFILL VENTI"
replace product="MUFFIN CRANBERRY ORANGE" if item_description=="MUFFIN CRANBERRY CORE"
replace product="SCONE CINNAMON CHIP" if item_description=="SCONE CINNAMON"
replace product="CREAM CHEESE LOWFAT" if item_description=="CREAM CHEESE LOWFAT"
replace product="COOKIE SNICKERDOODLE" if item_description=="COOKIE ICED"
replace product="" if item_description=="ESPRESSO BARISTA GRAPHITE BLK"
replace product="DECAF COFFEE SHORT" if item_description=="COFFEE DECAF SHORT"
replace product="DECAF COFFEE TALL" if item_description=="COFFEE DECAF TALL"
replace product="DECAF COFFEE GRANDE" if item_description=="COFFEE DECAF GRANDE"
replace product="DECAF COFFEE VENTI" if item_description=="COFFEE DECAF VENTI"
replace product="TAZO BLACK SHAKEN ICED TEA VENTI" if item_description=="SHAKEN ICED COFFEE VENTI"
replace product="TAZO CHAI ICED TEA LATTE VENTI" if item_description=="CHAI LATTE ICED VENTI"
replace product="ICED CAFFE LATTE VENTI" if item_description=="LATTE ICED VENTI"
replace product="ICED CAFFE MOCHA VENTI" if item_description=="MOCHA ICED VENTI"
replace product="ICED CAFFE AMERICANO VENTI" if item_description=="AMERICANO ICED VENTI"
replace product="APPLE JUICE VENTI" if item_description=="APPLE JUICE VENTI"
replace product="ESPRESSO FRAPPUCCINO BLENDED COFFEE VENTI" if item_description=="FRAPPUCCINO COFFEE VENTI"
replace product="MOCHA FRAPPUCCINO BLENDED COFFEE VENTI" if item_description=="FRAPPUCCINO MOCHA VENTI"
replace product="ESPRESSO FRAPPUCCINO BLENDED COFFEE VENTI" if item_description=="ESPRESSO FRAPPUCCINO 24OZ"
replace product="LIGHT FLAVORED SYRUP" if item_description=="LIGHT SF VANILLA SYRUP"
replace product="FLAVORED SYRUP" if item_description=="SF VANILLA SYRUP"
replace product="BAGEL CINNAMON RAISIN" if item_description=="BAGEL CINNAMON"
replace product="BAR BROWNIE WITH NUTS" if item_description=="BAR ESPRESSO BROWNIE"
replace product="" if item_description=="DOUGHNUT 6 PACK"
replace product="BAR CRANBERRY BLISS" if item_description=="BAR CRANBERRY BLISS"
replace product="" if item_description=="COFFEE TRAVELER 96OZ"
replace product="WHITE CHOCOLATE MOCHA SHORT" if item_description=="WHITE MOCHA SHORT"
replace product="WHITE CHOCOLATE MOCHA TALL" if item_description=="WHITE MOCHA TALL"
replace product="WHITE CHOCOLATE MOCHA GRANDE" if item_description=="WHITE MOCHA GRANDE"
replace product="WHITE CHOCOLATE MOCHA VENTI" if item_description=="WHITE MOCHA VENTI"
replace product="SANDWICH TURKEY AND JALEPENO HAVARTI" if item_description=="SANDWICH TURKEY & HAVARTI"
replace product="CAKE LOWFAT BLUEBERRY COFFEE" if item_description=="CAKE RF BLUEBERRY COFFEE"
replace product="CAKE LOWFAT CINNAMON SWIRL COFFEE" if item_description=="CAKE RF APPLE COFFEE"
replace product="CARAMEL FRAPPUCCINO BLENDED COFFEE TALL" if item_description=="FRAPPUCCINO CARAMEL TALL"
replace product="CARAMEL FRAPPUCCINO BLENDED COFFEE GRANDE" if item_description=="FRAPPUCCINO CARAMEL GRANDE"
replace product="CARAMEL FRAPPUCCINO BLENDED COFFEE VENTI" if item_description=="FRAPPUCCINO CARAMEL VENTI"
replace product="COOKIE OATMEAL RAISIN" if item_description=="COOKIE OATMEAL"
replace product="WHITE CHOCOLATE MOCHA TALL" if item_description=="WHITE MOCHA ICED TALL"
replace product="WHITE CHOCOLATE MOCHA GRANDE" if item_description=="WHITE MOCHA ICED GRANDE"
replace product="WHITE CHOCOLATE MOCHA VENTI" if item_description=="WHITE MOCHA ICED VENTI"
replace product="WHITE CHOCOLATE MOCHA FRAPPUCCINO BLENDED COFFEE TALL" if item_description=="FRAPPUCCINO WHITE MOCHA TALL"
replace product="WHITE CHOCOLATE MOCHA FRAPPUCCINO BLENDED COFFEE GRANDE" if item_description=="FRAPPUCCINO WHITE MOCHA GRANDE"
replace product="WHITE CHOCOLATE MOCHA FRAPPUCCINO BLENDED COFFEE VENTI" if item_description=="FRAPPUCCINO WHITE MOCHA VENTI"
replace product="SANDWICH TOMATO MOZARELLA" if item_description=="SANDWICH MOZZARELLA"
replace product="FLAVORED SYRUP" if item_description=="SHOT CARAMEL SYRUP"
replace product="MILK VENTI" if item_description=="MILK STEAMED VENTI"
replace product="BAR CRANBERRY BLISS" if item_description=="TRAY CRANBERRY BLISS"
replace product="FRAPPUCCINO CN MOCHA BTL 9.5OZ" if item_description=="FRAPPUCCINO CN MOCHA BTL 9.5oz"
replace product="WHITE HOT CHOCOLATE VENTI" if item_description=="HOT WHITE CHOCOLATE VENTI"
replace product="WHITE HOT CHOCOLATE GRANDE" if item_description=="HOT WHITE CHOCOLATE GRANDE"
replace product="WHITE HOT CHOCOLATE TALL" if item_description=="HOT WHITE CHOCOLATE TALL"
replace product="WHITE HOT CHOCOLATE SHORT" if item_description=="HOT WHITE CHOCOLATE SHORT"
replace product="WHITE HOT CHOCOLATE SHORT" if item_description=="HOT WHITE CHOC COCOA KIDS"
replace product="ICED CARAMEL MACCHIATO GRANDE" if item_description=="CARAMEL MACCHIATO ICED GRANDE"
replace product="ICED CARAMEL MACCHIATO TALL" if item_description=="CARAMEL MACCHIATO ICED TALL"
replace product="CARAMEL APPLE SPICE SHORT" if item_description=="APPLE SPICE CARAMEL SHORT"
replace product="CARAMEL APPLE SPICE TALL" if item_description=="APPLE SPICE CARAMEL TALL"
replace product="CARAMEL APPLE SPICE GRANDE" if item_description=="APPLE SPICE CARAMEL GRANDE"
replace product="CARAMEL APPLE SPICE VENTI" if item_description=="APPLE SPICE CARAMEL VENTI"
replace product="ICED CARAMEL MACCHIATO VENTI" if item_description=="CARAMEL MACCHIATO ICED VT 24OZ"
replace product="CARAMEL APPLE SPICE SHORT" if item_description=="APPLE SPICE CARAMEL KIDS"
replace product="FLAVORED SYRUP" if item_description=="SHOT CINNAMON SYRUP"
replace product="LIGHT FLAVORED SYRUP" if item_description=="LIGHT CARAMEL SYRUP"
replace product="FLAVORED SYRUP" if item_description=="CINNAMON SYRUP"
replace product="FLAVORED SYRUP" if item_description=="CARAMEL SYRUP"
replace product="" if item_description=="CHOCOLATE CHIPS"
replace product="SYRUP FLAVORED LATTE TALL" if item_description=="GINGERBREAD LATTE TALL"
replace product="SYRUP FLAVORED LATTE SHORT" if item_description=="GINGERBREAD LATTE SHORT"
replace product="SYRUP FLAVORED LATTE GRANDE" if item_description=="GINGERBREAD LATTE GRANDE"
replace product="SYRUP FLAVORED LATTE VENTI" if item_description=="GINGERSNAP LATTE VENTI"
replace product="" if item_description=="BARISTA KNOCK OUT ESPRESSO BOX"
replace product="FLAVORED SYRUP" if item_description=="SHOT GINGERBREAD SYRUP"
replace product="FLAVORED SYRUP" if item_description=="GINGERBREAD SYRUP"
replace product="" if item_description=="CLEANER DESCALER 6/1P"
replace product="2.5 OZ COFFEE" if item_description=="2.5 OZ COFFEE"
replace product="MILK TALL" if item_description=="ORGANIC MILK"
replace product="" if item_description=="SPECIALTY 2PACK CHOCO GRAHAM"
replace product="" if item_description=="COOKIE MADELEINE 3PK"
replace product="SANDWICH PEPPERED BACON EGG AND AGED CHEDDAR BREAKFAST" if item_description=="BREAKFAST HAM & EGG"
replace product="BOTTLE BULLET MIDNIGHT BLUE" if item_description=="BOTTLE BULLET MIDNIGHT BLUE"
replace product="GINGERBREAD HOLIDAY" if item_description=="SLICE HOLIDAY GINGERBREAD"
replace product="MILK SHORT" if item_description=="MILK US VANILLA RTD 8OZ ORGANC"
replace product="MILK TALL" if item_description=="MILK RTD VANILLA"
replace product="CHOCOLATE MILK TALL" if item_description=="MILK RTD CHOCOLATE"
replace product="SANDWICH PEPPERED BACON EGG AND AGED CHEDDAR BREAKFAST" if item_description=="BREAKFAST BACON EGG & CHEDDAR"
replace product="ICED SYRUP FLAVORED LATTE VENTI" if item_description=="GINGERSNAP LATTE ICED VENTI"
replace product="" if item_description=="CAFE GREEN ROOM RENTAL"
replace product="CUPCAKE TRIPLE CHOCOLATE" if item_description=="CUPCAKE TRIPLE CHOCOLATE"
replace product="LEMONADE BLENDED BEVERAGE TALL" if item_description=="SHAKEN TAZO LEMONADE TALL"
replace product="LEMONADE BLENDED BEVERAGE GRANDE" if item_description=="SHAKEN TAZO LEMONADE GRANDE"
replace product="LEMONADE BLENDED BEVERAGE VENTI" if item_description=="SHAKEN TAZO LEMONADE VENTI"
replace product="TAZO CHAI FRAPPUCCINO BLENDED CREME TALL" if item_description=="FRAPPUCCINO CHAI CREME TALL"
replace product="TAZO CHAI FRAPPUCCINO BLENDED CREME GRANDE" if item_description=="FRAPPUCCINO CHAI CREAM GRANDE"
replace product="TAZO CHAI FRAPPUCCINO BLENDED CREME VENTI" if item_description=="FRAPPUCCINO CHAI CREME VENTI"
replace product="FLAVORED SYRUP" if item_description=="SHOT CLASSIC SYRUP"
replace product="VANILLA LATTE SHORT" if item_description=="VANILLA LATTE SHORT"
replace product="VANILLA LATTE TALL" if item_description=="VANILLA LATTE TALL"
replace product="VANILLA LATTE GRANDE" if item_description=="VANILLA LATTE GRANDE"
replace product="VANILLA LATTE VENTI" if item_description=="VANILLA LATTE VENTI HOT"
replace product="ICED VANILLA LATTE VENTI" if item_description=="VANILLA LATTE 24OZ VENTI"
replace product="DOUBLESHOT US 6.5OZ CAN" if item_description=="DOUBLESHOT US 6.5OZ CAN"
replace product="" if item_description=="PRESS 8 C SIGNATURE"
replace product="SANDWICH EGG SALAD" if item_description=="SANDWICH EGG SALAD & HAVARTI"
replace product="SANDWICH TURKEY & SWISS WITH MAYO" if item_description=="SANDWICH SMOKED TURKEY & SWISS"
replace product="VANILLA CREME SHORT" if item_description=="VANILLA CREME SHORT"
replace product="VANILLA CREME TALL" if item_description=="VANILLA CREME TALL"
replace product="VANILLA CREME GRANDE" if item_description=="VANILLA CREME GRANDE"
replace product="VANILLA CREME VENTI" if item_description=="VANILLA CREME VENTI"
replace product="PEPPERMINT WHITE CHOCOLATE MOCHA SHORT" if item_description=="PEPPERMINT MOCHA SHORT"
replace product="PEPPERMINT WHITE CHOCOLATE MOCHA TALL" if item_description=="PEPPERMINT MOCHA TALL"
replace product="PEPPERMINT WHITE CHOCOLATE MOCHA GRANDE" if item_description=="PEPPERMINT MOCHA GRANDE"
replace product="PEPPERMINT WHITE CHOCOLATE MOCHA VENTI" if item_description=="PEPPERMINT MOCHA VENTI"
replace product="ICED PEPPERMINT WHITE CHOCOLATE MOCHA VENTI" if item_description=="PEPPERMINT MOCHA ICED VENIT"
replace product="PEPPERMINT HOT CHOCOLATE KIDS" if item_description=="PEPPERMINT HOT CHOCOLATE KIDS"
replace product="PEPPERMINT HOT CHOCOLATE SHORT" if item_description=="PEPPERMINT HOT CHOCOLATE SHORT"
replace product="PEPPERMINT HOT CHOCOLATE TALL" if item_description=="PEPPERMINT HOT CHOCOLATE TALL"
replace product="PEPPERMINT HOT CHOCOLATE GRANDE" if item_description=="PEPPERMINT HOT CHOCOLATE GRANDE"
replace product="PEPPERMINT HOT CHOCOLATE VENTI" if item_description=="PEPPERMINT HOT CHOCOLATE VENTI"
replace product="VANILLA BEAN FRAPPUCCINO BLENDED CREME TALL" if item_description=="CREME FRAPPUCCINO SYRUP TALL"
replace product="VANILLA CREME GRANDE" if item_description=="CREME SYRUP GRANDE"
replace product="ICED SYRUP FLAVORED CREME VENTI" if item_description=="CREME SYRUP ICED VENTI 24OZ"
replace product="SHOT CHAI" if item_description=="SHOT CHAI"
replace product="SHOT LIGHT CHAI" if item_description=="SHOT LIGHT CHAI"
replace product="SHOT CHAI" if item_description=="SHOT CHAI SYRUP"
replace product="PEPPERMINT WHITE CHOCOLATE MOCHA TALL" if item_description=="PEPP MOCHA FRAPPUCCINO TALL"
replace product="PEPPERMINT WHITE CHOCOLATE MOCHA GRANDE" if item_description=="PEPP MOCHA TWIST FRAPP GRANDE"
replace product="PEPPERMINT WHITE CHOCOLATE MOCHA VENTI" if item_description=="PEPP MOCHA TWIST FRAPP VENTI"
replace product="VANILLA CREME SHORT" if item_description=="CREME SYRUP SHORT"
replace product="VANILLA CREME TALL" if item_description=="CREME SYRUP TALL"
replace product="VANILLA CREME GRANDE" if item_description=="CREME SYRUP GRANDE"
replace product="VANILLA CREME VENTI" if item_description=="CREME SYRUP VENTI"
replace product="ICED VANILLA LATTE TALL" if item_description=="LATTE VANILLA ICED TALL"
replace product="ICED VANILLA LATTE GRANDE" if item_description=="LATTE VANILLA ICED GRANDE"
replace product="YOGURT STRAWBERRY" if item_description=="YOGURT STRAWBERRY"
replace product="JUICE ODWALLA C MONSTER 325ML" if item_description=="JUICE ODWALLA C MONSTER 325ml"
replace product="JUICE ODWALLA ORANGE 325ML" if item_description=="JUICE ODWALLA ORANGE 325ml"
replace product="JUICE ODWALLA STRAWBERRY BANANA 325ML" if item_description=="JUICE ODWALLA STRAW/BAN 325ml"
replace product="TAZO BLACK SHAKEN ICED TEA LEMONADE TALL" if item_description=="SHAKEN ICED TEA BLACK SWEET TALL"
replace product="TAZO BLACK SHAKEN ICED TEA LEMONADE GRANDE" if item_description=="SHAKEN ICED TEA BLACK SWEET GRANDE"
replace product="TAZO BLACK SHAKEN ICED TEA LEMONADE VENTI" if item_description=="SHAKEN ICED TEA BLACK SWEET VENTI"
replace product="TAZO PASSION SHAKEN ICED TEA TALL" if item_description=="SHAKEN TEA PASSION SWT ICD TALL"
replace product="TAZO PASSION SHAKEN ICED TEA GRANDE" if item_description=="SHAKEN TEA PASSION SWT ICD GRANDE"
replace product="TAZO PASSION SHAKEN ICED TEA VENTI" if item_description=="SHAKEN TEA PASSION SWT ICD VENTI"
replace product="TAZO BLACK SHAKEN ICED TEA LEMONADE TALL" if item_description=="SHAKEN TEA LEMONADE PASSION TALL"
replace product="TAZO BLACK SHAKEN ICED TEA LEMONADE GRANDE" if item_description=="SHAKEN TEA LEMONADE PASSION GRANDE"
replace product="TAZO BLACK SHAKEN ICED TEA LEMONADE VENTI" if item_description=="SHAKEN TEA LEMONADE PASSION VENTI"
replace product="ICED SYRUP FLAVORED LATTE TALL" if item_description=="GINGERSNAP LATTE ICED TALL"
replace product="ICED SYRUP FLAVORED LATTE GRANDE" if item_description=="GINGERSNAP LATTE ICED GRANDE"
replace product="ICED PEPPERMINT WHITE CHOCOLATE MOCHA TALL" if item_description=="PEPPERMINT MOCHA ICED TALL"
replace product="ICED PEPPERMINT WHITE CHOCOLATE MOCHA WHIP GRANDE" if item_description=="PEPPERMINT MOCHA ICED GRANDE"
replace product="FLAVORED SYRUP" if item_description=="SHOT PEPPERMINT SYRUP"
replace product="LIGHT FLAVORED SYRUP" if item_description=="SHOT LT PEPPERMINT SYRUP"
replace product="FLAVORED SYRUP" if item_description=="SHOT EX PEPPERMINT SYRUP"
replace product="FLAVORED SYRUP" if item_description=="SHOT TOFFEE NUT SYRUP"
replace product="LIGHT FLAVORED SYRUP" if item_description=="SHOT LT TOFFEE NUT SYRUP"
replace product="FLAVORED SYRUP" if item_description=="SHOT EX TOFFEE NUT SYRUP"
replace product="" if item_description=="SCONE MINI PK/12"
replace product="VANILLA BEAN FRAPPUCCINO BLENDED CREME TALL" if item_description=="VANILLA BEAN CREME FRAPP TALL"
replace product="VANILLA BEAN FRAPPUCCINO BLENDED CREME GRANDE" if item_description=="VANILLA BEAN CREME FRAPP GRAND"
replace product="VANILLA BEAN FRAPPUCCINO BLENDED CREME VENTI" if item_description=="VANILLA BEAN CREME FRAPP VENTI"
replace product="FLAVORED FRAPPUCCINO BLENDED COFFEE TALL" if item_description=="CAFE VANILLA FRAPPUCCINO TALL"
replace product="FLAVORED FRAPPUCCINO BLENDED COFFEE GRANDE" if item_description=="CAFE VANILLA FRAPPUCCINO GRANDE"
replace product="FLAVORED FRAPPUCCINO BLENDED COFFEE VENTI" if item_description=="CAFE VANILLA FRAPPUCCINO VENTI"
replace product="DOUBLE CHOCOLATY CHIP FRAPPUCCINO BLENDED CREME TALL" if item_description=="FRAPP DOUBL CHOC CHIP CREME TALL"
replace product="DOUBLE CHOCOLATY CHIP FRAPPUCCINO BLENDED CREME VENTI" if item_description=="CHOCOLATE CHIP CREME FRAPP VENTI"
replace product="JAVA CHIP FRAPPUCCINO BLENDED COFFEE TALL" if item_description=="JAVA CHIP COFFEE FRAPP TALL"
replace product="JAVA CHIP FRAPPUCCINO BLENDED COFFEE GRANDE" if item_description=="JAVA CHIP COFFEE FRAPP GRANDE"
replace product="JAVA CHIP FRAPPUCCINO BLENDED COFFEE VENTI" if item_description=="JAVA CHIP COFFEE FRAPP VENTI"
replace product="TAZO GREEN TEA FRAPPUCCINO BLENDED CREME TALL" if item_description=="GREEN TEA CREME FRAP TALL"
replace product="TAZO GREEN TEA FRAPPUCCINO BLENDED CREME GRANDE" if item_description=="GREEN TEA CREME FRAP GRANDE"
replace product="TAZO GREEN TEA FRAPPUCCINO BLENDED CREME VENTI" if item_description=="GREEN TEA CREME FRAP VENTI"
replace product="BAR CHOCOLATE DARK RASPBERRY" if item_description=="CHOC US BAR DRK RASPBERRY"
replace product="DOUBLE CHOCOLATY CHIP FRAPPUCCINO BLENDED CREME GRANDE" if item_description=="GR CHOCOLATE CHIP CREME FRAPP"
replace product="STRAWBERRIES & CREME FRAPPUCCINO BLENDED CREME TALL" if item_description=="STRAWBERRY AND CREME FRAPP TALL"
replace product="STRAWBERRIES & CREME FRAPPUCCINO BLENDED CREME GRANDE" if item_description=="STRAWBERRY AND CREME FRAPP GRANDE"
replace product="STRAWBERRIES & CREME FRAPPUCCINO BLENDED CREME VENTI" if item_description=="STRAWBERRY AND CREME FRAPP VENTI"
replace product="COFFEE FRAPPUCCINO BLENDED COFFEE GRANDE" if item_description=="COFFEE CUBED FRAPPUCCINO GRANDE"
replace product="" if item_description=="VANILLA BEAN"
replace product="BAR FRUIT COBBLER" if item_description=="BAR FRUIT COBBLER"
replace product="FLAVORED SYRUP" if item_description=="SYRUP CLASSIC"
replace product="" if item_description=="CAKE COFFEE TRAY"
replace product="MUFFIN MINI" if item_description=="MUFFIN MINI SINGLE"
replace product="COOKIE MINI DAYBREAK WITH NUTS" if item_description=="COOKIE MINI"
replace product="DANISH MINI" if item_description=="MINI SWEETROLL DANISH SINGLE"
replace product="" if item_description=="SALAD SPA"
replace product="SANDWICH TURKEY & SWISS WITH MAYO" if item_description=="SANDWICH TURKEY & SWISS CORE"
replace product="SANDWICH HAM AND WHITE CHEDDAR" if item_description=="SANDWICH SMOKED HAM&CHEDDAR"
replace product="STRAWBERRY" if item_description=="STRAWBERRY"
replace product="PUMPKIN SPICE LATTE SHORT" if item_description=="LATTE PUMPKIN SPICE SHORT"
replace product="PUMPKIN SPICE LATTE TALL" if item_description=="LATTE PUMPKIN SPICE TALL"
replace product="PUMPKIN SPICE LATTE GRANDE" if item_description=="LATTE PUMPKIN SPICE GRANDE"
replace product="PUMPKIN SPICE LATTE VENTI" if item_description=="LATTE PUMPKIN SPICE VENTI"
replace product="ICED PUMPKIN SPICE LATTE TALL" if item_description=="LATTE PUMPKIN SPICE ICED TALL"
replace product="ICED PUMPKIN SPICE LATTE GRANDE" if item_description=="LATTE PUMPKIN SPICE ICED GRANDE"
replace product="ICED PUMPKIN SPICE LATTE VENTI" if item_description=="LATTE PUMPKIN SPICE ICED VENTI"
replace product="PUMPKIN SPICE CREME SHORT" if item_description=="CREME PUMPKIN SPICE SHORT"
replace product="PUMPKIN SPICE CREME TALL" if item_description=="CREME PUMPKIN SPICE TALL"
replace product="PUMPKIN SPICE CREME GRANDE" if item_description=="CREME PUMPKIN SPICE GRANDE"
replace product="PUMPKIN SPICE CREME VENTI" if item_description=="CREME PUMPKIN SPICE VENTI"
replace product="PUMPKIN SPICE FRAPPUCCINO BLENDED COFFEE TALL" if item_description=="FRAPP PUMPKIN SPICE CREME TAL"
replace product="PUMPKIN SPICE FRAPPUCCINO BLENDED COFFEE GRANDE" if item_description=="FRAPP PUMPKIN SPICE CREME GRANDE"
replace product="PUMPKIN SPICE FRAPPUCCINO BLENDED COFFEE VENTI" if item_description=="FRAPP SPICE PUMPKIN CREME VENTI"
replace product="FRUIT BOWL SEASONAL" if item_description=="FRUIT BOWL SEASONAL"
replace product="LIGHT FLAVORED SYRUP" if item_description=="LIGHT CLASSIC SYRUP"
replace product="PLATE FRUIT AND CHEESE" if item_description=="FRUIT AND CHEESE"
replace product="" if item_description=="SYRUP CINN DOLCE 1L WEST"
replace product="" if item_description=="SYRUP CINN DOLCE 1L EAST"
replace product="CINNAMON DOLCE LATTE SHORT" if item_description=="LATTE CINNAMON DOLCE SHORT"
replace product="CINNAMON DOLCE LATTE TALL" if item_description=="LATTE CINNAMON DOLCE TALL"
replace product="CINNAMON DOLCE LATTE GRANDE" if item_description=="LATTE CINNAMON DOLCE GRANDE"
replace product="CINNAMON DOLCE LATTE VENTI" if item_description=="LATTE CINNAMON DOLCE VENTI"
replace product="ICED SYRUP FLAVORED LATTE TALL" if item_description=="LATTE CINNAMON DOLCE ICD TALL"
replace product="ICED SYRUP FLAVORED LATTE GRANDE" if item_description=="LATTE CINNAMON DOLCE ICD GRANDE"
replace product="ICED SYRUP FLAVORED LATTE VENTI" if item_description=="LATTE CINNAMON DOLCE ICD VENTI"
replace product="CINNAMON DOLCE CREME TALL" if item_description=="CREME CINNAMON DOLCE TALL"
replace product="CINNAMON DOLCE CREME GRANDE" if item_description=="CREME CINNAMON DOLCE GRANDE"
replace product="CINNAMON DOLCE CREME VENTI" if item_description=="CREME CINNAMON DOLCE VENTI"
replace product="CINNAMON DOLCE FRAPPUCCINO BLENDED COFFEE TALL" if item_description=="FRAPP CINNAMON DOLCE TALL"
replace product="CINNAMON DOLCE FRAPPUCCINO BLENDED COFFEE GRANDE" if item_description=="FRAPP CINNAMON DOLCE GRANDE"
replace product="CINNAMON DOLCE FRAPPUCCINO BLENDED COFFEE VENTI" if item_description=="FRAPP CINNAMON DOLCE VENTI"
replace product="FLAVORED SYRUP" if item_description=="SHOT CINNAMON DOLCE SYRUP"
replace product="MUFFIN LOWFAT CARAMEL PRALINE" if item_description=="MUFFIN RF CARAMEL PRALINE"
replace product="JUICE ODWALLA SUPERFOOD 325ML" if item_description=="JUICE ODWALLA SUPERFOOD 325ml"
replace product="JUICE ODWALLA TANGERINE 325ML" if item_description=="JUICE ODWALLA TANGERINE 325ml"
replace product="WATER" if item_description=="WATER SAN PELLEGRINO 250ML US"
replace product="JUICE ODWALLA ORANGE 450ML" if item_description=="JUICE ODWALLA ORANGE 15.2OZ US"
replace product="SODA JONES ROOT BEER" if item_description=="SODA JONES ROOT BEER"
replace product="SODA JONES DIET" if item_description=="SODA JONES DIET BLACK CHERRY"
replace product="BAR ZEBRA" if item_description=="BAR ZEBRA"
replace product="ESPRESSO FRAPPUCCINO LIGHT BLENDED COFFEE TALL" if item_description=="FRAPPUCCINO LIGHT COFFEE TALL"
replace product="ESPRESSO FRAPPUCCINO LIGHT BLENDED COFFEE GRANDE" if item_description=="FRAPPUCCINO LIGHT COFFEE GRAND"
replace product="ESPRESSO FRAPPUCCINO LIGHT BLENDED COFFEE VENTI" if item_description=="FRAPPUCCINO LIGHT COFFEE VENTI"
replace product="MOCHA FRAPPUCCINO LIGHT BLENDED COFFEE TALL" if item_description=="FRAPPUCCINO LIGHT MOCHA TALL"
replace product="MOCHA FRAPPUCCINO LIGHT BLENDED COFFEE GRANDE" if item_description=="FRAPPUCCINO LIGHT MOCHA GRANDE"
replace product="MOCHA FRAPPUCCINO LIGHT BLENDED COFFEE VENTI" if item_description=="FRAPPUCCINO LIGHT MOCHA VENTI"
replace product="CARAMEL FRAPPUCCINO LIGHT BLENDED COFFEE TALL" if item_description=="FRAPPUCCINO LIGHT CARAMEL TALL"
replace product="CARAMEL FRAPPUCCINO LIGHT BLENDED COFFEE GRANDE" if item_description=="FRAPPUCCINO LIGHT CARAMEL GRANDE"
replace product="CARAMEL FRAPPUCCINO LIGHT BLENDED COFFEE VENTI" if item_description=="FRAPPUCCINO LIGHT CARAMEL VENTI"
replace product="ESPRESSO FRAPPUCCINO LIGHT BLENDED COFFEE TALL" if item_description=="FRAPPUCCINO LIGHT ESPRESSO TALL"
replace product="ESPRESSO FRAPPUCCINO LIGHT BLENDED COFFEE GRANDE" if item_description=="FRAPPUCCINO LIGHT ESPRESSO GRANDE"
replace product="ESPRESSO FRAPPUCCINO LIGHT BLENDED COFFEE VENTI" if item_description=="FRAPPUCCINO LIGHT ESPRESSO VENTI"
replace product="WHITE CHOCOLATE MOCHA FRAPPUCCINO LIGHT BLENDED COFFEE TALL" if item_description=="WHITE CHOCOLATE FRAP LIGHT TALL"
replace product="WHITE CHOCOLATE MOCHA FRAPPUCCINO LIGHT BLENDED COFFEE GRANDE" if item_description=="WHITE CHOCOLATE FRAP LIGHT GRANDE"
replace product="WHITE CHOCOLATE MOCHA FRAPPUCCINO LIGHT BLENDED COFFEE VENTI" if item_description=="WHITE CHOCOLATE FRAP LIGHT VENTI"
replace product="CAFFE VANILLA FRAPPUCCINO LIGHT BLENDED COFFEE TALL" if item_description=="CAFE VANILLA FRAP LIGHT TALL"
replace product="CAFFE VANILLA FRAPPUCCINO LIGHT BLENDED COFFEE GRANDE" if item_description=="CAFE VANILLA FRAP LIGHT GRANDE"
replace product="CAFFE VANILLA FRAPPUCCINO LIGHT BLENDED COFFEE VENTI" if item_description=="CAFE VANILLA FRAP LIGHT VENTI"
replace product="JAVA CHIP FRAPPUCCINO LIGHT BLENDED COFFEE TALL" if item_description=="FRAPP LIGHT JAVA CHIP TALL"
replace product="JAVA CHIP FRAPPUCCINO LIGHT BLENDED COFFEE GRANDE" if item_description=="FRAPP LIGHT JAVA CHIP GRANDE"
replace product="JAVA CHIP FRAPPUCCINO LIGHT BLENDED COFFEE VENTI" if item_description=="FRAPP LIGHT JAVA CHIP VENTI"
replace product="BROWNIE PEPPERMINT" if item_description=="BROWNIE PEPPERMINT"
replace product="CAKE LOWFAT CINNAMON SWIRL COFFEE" if item_description=="CCAKE RF CINNAMON SWIRL"
replace product="FLAVORED SYRUP" if item_description=="SYRUP CINNAMON STEUSEL"
replace product="PEPPERMINT MOCHA FRAPPUCCINO LIGHT BLENDED COFFEE TALL" if item_description=="PEPP MOCHA FRAPP LIGHT TALL"
replace product="PEPPERMINT MOCHA FRAPPUCCINO LIGHT BLENDED COFFEE GRANDE" if item_description=="PEPP MOCHA FRAPP LIGHT GRANDE"
replace product="PEPPERMINT MOCHA FRAPPUCCINO LIGHT BLENDED COFFEE VENTI" if item_description=="PEPP MOCHA FRAPP LIGHT VENTI"
replace product="FRAPPUCCINO DECAF BROWNIE GRANDE" if item_description=="FRAPPUCCINO DECAF BROWNIE GRANDE"
replace product="SODA JONES CREAM" if item_description=="SODA JONES CREAM"
replace product="BAR OAT FUDGE" if item_description=="BAR OAT FUDGE"
replace product="JUICE ODWALLA APPLE 325ML" if item_description=="JUICE ODWALLA APPLE 325ml"
replace product="TAZO BLACK SHAKEN ICED TEA TALL" if item_description=="TAZO ICED TEA RTD"
replace product="SANDWICH HAM AND WHITE CHEDDAR" if item_description=="SANDWICH HAM & BRIE"
replace product="SALAD FRUIT" if item_description=="SALAD CITRUS"
replace product="SALAD FRUIT" if item_description=="SALAD DELUXE FRUIT"
replace product="SALAD FRUIT" if item_description=="SALAD FRUIT W/STRAWBERRIES"
replace product="SALAD FRUIT" if item_description=="SALAD FRUIT W/APPLES"
replace product="HEAVY CREAM" if item_description=="HEAVY CREAM"
replace product="TAZO GREEN SHAKEN ICED TEA TALL" if item_description=="SHAKEN ICED TEA GREEN SWEET TALL"
replace product="TAZO GREEN SHAKEN ICED TEA GRANDE" if item_description=="SHAKEN ICED TEA GREEN SWEET GRANDE"
replace product="TAZO GREEN SHAKEN ICED TEA VENTI" if item_description=="SHAKEN ICED TEA GREEN SWEET VENTI"
replace product="TAZO GREEN SHAKEN ICED TEA LEMONADE TALL" if item_description=="SHAKEN ICED GREEN TEA LEM TALL"
replace product="TAZO GREEN SHAKEN ICED TEA LEMONADE GRANDE" if item_description=="SHAKEN ICED GREEN TEA LEM GRANDE"
replace product="TAZO GREEN SHAKEN ICED TEA LEMONADE VENTI" if item_description=="SHAKEN ICED GREEN TEA LEM VENTI"
replace product="MIXED VEGGIES" if item_description=="MIXED VEGGIES"
replace product="CHEDDAR CLASSIC SAUSAGE EGG AND AGED" if item_description=="BREAKFAST SAUSAGE EGG & CHEESE"
replace product="LEMONADE BLENDED BEVERAGE TALL" if item_description=="BLENDED LEMONADE STRAW TALL"
replace product="LEMONADE BLENDED BEVERAGE GRANDE" if item_description=="BLENDED LEMONADE STRAW GRANDE"
replace product="LEMONADE BLENDED BEVERAGE VENTI" if item_description=="BLENDED LEMONADE STRAW VENTI"
replace product="BUN MORNING" if item_description=="MORNING BUN"
replace product="BREAKFAST EGGS FLORENTINE" if item_description=="BREAKFAST EGGS FLORENTINE"
replace product="BAR BLUEBERRY" if item_description=="BAR BLUEBERRY ORGANIC"
replace product="MUFFIN CRANBERRY ORANGE" if item_description=="MUFFIN CRANBERRY ORANGE"
replace product="PUMPKIN SPICE FRAPPUCCINO LIGHT BLENDED COFFEE TALL" if item_description=="FRAPPUCCINO LIGHT PUMPKIN TALL"
replace product="PUMPKIN SPICE FRAPPUCCINO LIGHT BLENDED COFFEE GRANDE" if item_description=="FRAPPUCCINO LIGHT PMKIN GRANDE"
replace product="PUMPKIN SPICE FRAPPUCCINO LIGHT BLENDED COFFEE VENTI" if item_description=="FRAPPUCCINO LIGHT PMKIN VENTI"
replace product="FLAVORED SYRUP" if item_description=="SUBSTITUTE PUMPKIN SYRUP"
replace product="PUMPKIN SPICE FRAPPUCCINO BLENDED COFFEE TALL" if item_description=="FRAPP PUMPKIN SPICE TALL"
replace product="PUMPKIN SPICE FRAPPUCCINO BLENDED COFFEE GRANDE" if item_description=="FRAPP PUMPKIN SPICE GRANDE"
replace product="PUMPKIN SPICE FRAPPUCCINO BLENDED COFFEE VENTI" if item_description=="FRAPP SPICE PUMPKIN VENTI"
replace product="SANDWICH CHICKEN SALAD" if item_description=="SANDWICH TARRAGON CHICKEN SALA"
replace product="FLAVORED SYRUP" if item_description=="SHOT SF HAZELNUT"
replace product="LIGHT FLAVORED SYRUP" if item_description=="LIGHT SF HAZELNUT SYRUP"
replace product="FLAVORED SYRUP" if item_description=="SF HAZELNUT SYRUP"
replace product="CHEDDAR LOWFAT TURKEY BACON CHOLESTEROL-FREE EGG LOWFAT WHITE" if item_description=="BREAKFAST RF TURKEY BACON"
replace product="MINT MOCHA CHIP FRAPPUCCINO BLENDED COFFEE WITH CHOCOLATE WHIPPED CREAM TALL" if item_description=="FRAPPUCCINO MINT MOCHA CHIP TALL"
replace product="MINT MOCHA CHIP FRAPPUCCINO BLENDED COFFEE WITH CHOCOLATE WHIPPED CREAM GRANDE" if item_description=="FRAPPUCCINO MINT MOCHA CHIP GRANDE"
replace product="MINT MOCHA CHIP FRAPPUCCINO BLENDED COFFEE WITH CHOCOLATE WHIPPED CREAM VENTI" if item_description=="FRAPPUCCINO MINT MOCHA CHIP VENTI"
replace product="MINT CHOCOLATY CHIP FRAPPUCCINO BLENDED CREME WITH CHOCOLATE WHIPPED CREAM TALL" if item_description=="FRAPP MINT CHOCO CHIP CREME TALL"
replace product="MINT CHOCOLATY CHIP FRAPPUCCINO BLENDED CREME WITH CHOCOLATE WHIPPED CREAM GRANDE" if item_description=="FRAPP MINT CHOCO CHIP CREME GRANDE"
replace product="MINT CHOCOLATY CHIP FRAPPUCCINO BLENDED CREME WITH CHOCOLATE WHIPPED CREAM VENTI" if item_description=="FRAPP MINT CHOCO CHIP CREME VENTI"
replace product="MINT MOCHA CHIP FRAPPUCCINO LIGHT BLENDED COFFEE TALL" if item_description=="FRAPP MINT MOCHA CHIP LIGHT TALL"
replace product="MINT MOCHA CHIP FRAPPUCCINO LIGHT BLENDED COFFEE GRANDE" if item_description=="FRAPP MINT MOCHA CHIP LIGHT GRANDE"
replace product="MINT MOCHA CHIP FRAPPUCCINO LIGHT BLENDED COFFEE VENTI" if item_description=="FRAPP MINT MOCHA CHIP LIGHT VENTI"
replace product="MADE ESPRESSO BROWNIE WITH STARBUCKS KENYA COFFEE" if item_description=="ESPRESSO FUDGE BROWNIE"
replace product="CAKE BANANA NUT LOAF" if item_description=="CAKE NSA BANANA NUT"
replace product="PACK BROWNIE BITES - 3" if item_description=="BROWNIE MINI BITES"
replace product="PACK BROWNIE BITES - 3" if item_description=="BROWNIE MINI BITES 3PK"
replace product="CAKE CHOCOLATE CARAMEL VOLCANO" if item_description=="CAKE WARM CHOCO MOLTEN"
replace product="MATCHA POWDER" if item_description=="MATCHA POWDER"
replace product="BAR CHEWY MARSHMALLOW" if item_description=="BAR CHEWY MARSHMALLOW"
replace product="SANDWICH TURKEY AND JALEPENO HAVARTI" if item_description=="SANDWICH TURKEY PESTO BAGUETTE"
replace product="SANDWICH TURKEY AND JALEPENO HAVARTI" if item_description=="SANDWICH CHICKEN CLUB CORE"
replace product="CARAMEL MOCHA VENTI" if item_description=="CARAMEL MOCHA 20 OZ VENTI"
replace product="CARAMEL MOCHA 24OZ" if item_description=="CARAMEL MOCHA 24OZ VENTI"
replace product="BANANA" if item_description=="BANANA WHOLE FRUIT"
replace product="COOKIE DOUBLE CHOCOLATE" if item_description=="COOKIE DOUBLE CHOCOLATE"
replace product="WATER" if item_description=="ETHOS BOTTLED WATER 700ML"
replace product="JUICE ODWALLA CARROT 325ML" if item_description=="JUICE ODWALLA CARROT 325ml"
replace product="JUICE ODWALLA BBERRIER 450ML" if item_description=="JUICE ODWALLA BBERRIER 450ml"
replace product="BAR APRICOT GRANOLA" if item_description=="BAR APRICOT GRANOLA"
replace product="FLAVORED SYRUP" if item_description=="SHOT MINT CHOCOLATE"
replace product="LIGHT FLAVORED SYRUP" if item_description=="SHOT LT MINT CHOCO SYRUP"
replace product="FLAVORED SYRUP" if item_description=="SHOT EX MINT CHOCO SYRUP"
replace product="JUICE IZZE SPRKLNG POMEGRANATE" if item_description=="JUICE IZZE SPRKLNG POMEGRANATE"
replace product="FLAVORED SYRUP" if item_description=="SHOT MELON SYRUP"
replace product="LIGHT FLAVORED SYRUP" if item_description=="LT MELON SYRUP"
replace product="FLAVORED SYRUP" if item_description=="SHOT EX MELON SYRUP"
replace product="SANDWICH TARRAGON CHICKEN" if item_description=="SANDWICH TARRAGON CHICKEN CORE"
replace product="SCONE PETITE VANILLA" if item_description=="SCONE VANILLA PETITE"
replace product="" if item_description=="BIALETTI STOVE TOP"
replace product="" if item_description=="SCONE PETITE VANILLA 3PK"
replace product="TANGERINE FRAPP JUICE BLEND TALL" if item_description=="TANGERINE FRAPP JUICE BLEND TALL"
replace product="TANGERINE FRAPP JUICE BLEND GRANDE" if item_description=="TANGERINE FRAPP JUICE BLEND GRANDE"
replace product="TANGERINE FRAPP JUICE BLEND VENTI" if item_description=="TANGERINE FRAPP JUICE BLEND VENTI"
replace product="MUFFIN MINI" if item_description=="MUFFIN MINI BRAN"
replace product="DOUGHNUT PEPPERMINT" if item_description=="DOUGHNUT PEPPERMINT"
replace product="SCONE GINGERBREAD" if item_description=="SCONE GINGERBREAD"
replace product="JUICE ODWALLA MANGO TANGO 325ML" if item_description=="ODWALLA MANGO TANGO 325ml"
replace product="TAZO GREEN TEA LATTE SHORT" if item_description=="GREEN TEA LATTE SHORT"
replace product="TAZO GREEN TEA LATTE TALL" if item_description=="GREEN TEA LATTE TALL"
replace product="ICED TAZO GREEN TEA LATTE TALL" if item_description=="GREEN TEA LATTE TALL ICE"
replace product="TAZO GREEN TEA LATTE GRANDE" if item_description=="GREEN TEA LATTE GRANDE"
replace product="ICED TAZO GREEN TEA LATTE GRANDE" if item_description=="GREEN TEA LATTE GRANDE ICE"
replace product="TAZO GREEN TEA LATTE VENTI" if item_description=="GREEN TEA LATTE VENTI"
replace product="ICED TAZO GREEN TEA LATTE VENTI" if item_description=="GREEN TEA LATTE VENTI ICE"
replace product="" if item_description=="ETHOS BOTTLE WATER 700ml CS/24"
replace product="TAZO GREEN SHAKEN ICED TEA TALL" if item_description=="TAZO GREEN ICED FB"
replace product="BANANA CHOCOLATE BLEND WITH ESPRESSO SHOT GRANDE" if item_description=="COCOA ESPRESSO TALL"
replace product="FRAPPUCCINO LIGHT EGGNOG GRANDE" if item_description=="FRAPPUCCINO LT EGGNOG GRANDE"
replace product="LIGHT FLAVORED SYRUP" if item_description=="LIGHT CINNAMON DOLCE SYRUP"
replace product="FLAVORED SYRUP" if item_description=="CINNAMON DOLCE SYRUP"
replace product="CINNAMON DOLCE FRAPPUCCINO LIGHT BLENDED COFFEE TALL" if item_description=="CINN DOL FRAP LT BLENDED TALL"
replace product="CINNAMON DOLCE FRAPPUCCINO LIGHT BLENDED COFFEE GRANDE" if item_description=="CINN DOL FRAP LT BLENDED GRANDE"
replace product="CINNAMON DOLCE FRAPPUCCINO LIGHT BLENDED COFFEE VENTI" if item_description=="CINN DOL FRAP LT BLENDED VENTI"
replace product="SANDWICH TOMATO MOZARELLA" if item_description=="SAND TOMATO MOZZ CORE"
replace product="WHITE CHOCOLATE MOCHA FRAPPUCCINO BLENDED COFFEE TALL" if item_description=="WHITE CHOCOLATE FRAPP BL CR TALL"
replace product="WHITE CHOCOLATE MOCHA FRAPPUCCINO BLENDED COFFEE GRANDE" if item_description=="WHITE CHOCOLATE FRAPP BL CR GRANDE"
replace product="WHITE CHOCOLATE MOCHA FRAPPUCCINO BLENDED COFFEE VENTI" if item_description=="WHITE CHOCOLATE FRAPP BL CR VENTI"
replace product="BANANA COCONUT FRAPPUCCINO VENTI" if item_description=="BANANA COCONUT FRAPP VENTI"
replace product="" if item_description=="CAKE CUPCAKES 4 PACK - US"
replace product="SYRUP FLAVORED LATTE SHORT" if item_description=="LEPRECHAUN LATTE SHORT"
replace product="SYRUP FLAVORED LATTE TALL" if item_description=="LEPRECHAUN LATTE TALL"
replace product="SYRUP FLAVORED LATTE GRANDE" if item_description=="LEPRECHAUN LATTE GRANDE"
replace product="SYRUP FLAVORED LATTE VENTI" if item_description=="LEPRECHAUN LATTE VENTI"
replace product="MARBLE MOCHA MACCHIATO SHORT" if item_description=="MARBLE MOCHA MACCHIATO SHORT"
replace product="MARBLE MOCHA MACCHIATO TALL" if item_description=="MARBLE MOCHA MACCHIATO TALL"
replace product="MARBLE MOCHA MACCHIATO ICED TALL" if item_description=="MARBLE MOCHA MACCHIATO ICED TALL"
replace product="MARBLE MOCHA MACCHIATO GRANDE" if item_description=="MARBLE MOCHA MACCHIATO GRANDE"
replace product="MARBLE MOCHA MACCHIATO ICED GRANDE" if item_description=="MARBLE MOCHA MACCHIATO ICED GRANDE"
replace product="MARBLE MOCHA MACCHIATO VENTI" if item_description=="MARBLE MOCHA MACCHIATO VENTI"
replace product="MARBLE MOCHA MACCHIATO ICED VENTI" if item_description=="MARBLE MOCHA MACCHIATO ICED VENTI"
replace product="SANDWICH TURKEY AND JALEPENO HAVARTI" if item_description=="SMOKED TURKEY/HAVARTY"
replace product="MUFFIN CHOCOLATE CREAM CHEESE" if item_description=="MUFFIN CHOCO CREAMCHEESE"
replace product="CAKE CHOCOLATE CHIP COFFEE" if item_description=="COFFEE CAKE RF BAN CHOCO CHIP"
replace product="JUICE ODWALLA STRAWBERRY LEMONADE 450ML" if item_description=="JUICE ODWALLA STRWBRY LEM 450m"
replace product="SANDWICH TURKEY & SWISS WITH MAYO" if item_description=="SANDWICH TURKEY PEPP JACK"
replace product="CAFFE MISTO/CAFE AU LAIT TALL" if item_description=="ICED CAFE CON LECHE TALL"
replace product="CAFFE MISTO/CAFE AU LAIT GRANDE" if item_description=="ICED CAFE CON LECHE GRANDE"
replace product="CAFFE MISTO/CAFE AU LAIT VENTI" if item_description=="ICED CAFE CON LECHE VENTI"
replace product="" if item_description=="BISCOTTI US W/STOCKING HOL07"
replace product="" if item_description=="GUIDE SEATTLE PARKS RESOURCE"
replace product="YOGURT PARFAIT" if item_description=="YOGURT PARFAIT"
replace product="BAR TOFFEE ALMOND" if item_description=="BAR HONEY ALMOND"
replace product="" if item_description=="ESPRESSO RIALTO 4500"
replace product="" if item_description=="ESPRESSO MACH ASCASO DREAM HL7"
replace product="" if item_description=="PRESS W/TIMER 8CUP WINGED"
replace product="" if item_description=="SUB CREME"
replace product="MUFFIN WHOLE WHEAT MULTIBERRY" if item_description=="MUFFIN WHOLE WHEAT MULITIBERRY"
replace product="JUICE IZZE SPARKLING APPLE" if item_description=="JUICE IZZE SPARKLING APPLE"
replace product="" if item_description=="PRESS TEA FY07"
replace product="FLAVORED SYRUP" if item_description=="JUICY RASPBERRY SYRUP"
replace product="BAR FRUIT AND GRAIN" if item_description=="BAR FRUIT & GRAIN"
replace product="" if item_description=="BREWER 8CUP WHITE VENUS"
replace product="BOTTLE 0.5L WINTER PLAYFUL POP" if item_description=="BOTTLE 0.5L WINTER PLAYFUL POP"
replace product="SANDWHICH LOWFAT TURKEY" if item_description=="SAND LF SMOKED TURK WITH MULTI"
replace product="SANDWHICH LOWFAT TURKEY" if item_description=="SAND LF SMOKED TURK ARTICHOKE"
replace product="BAGEL FRENCH TOAST" if item_description=="BAGEL FRENCH TOAST"
replace product="" if item_description=="BREWER 8CUP VENUS DESIGN"
replace product="" if item_description=="PRESS 16oz BODUM TRAVEL PLASTC"
replace product="" if item_description=="PRESS 8oz TRAVEL BODUM PLASTIC"
replace product="DOUGHNUT TOP POT CHOCOLATE OLD FASHIONED" if item_description=="DOUGHNUT CHOCOLATE OLD FASHION"
replace product="VITAMIN WATER 20OZ" if item_description=="VITAMIN WATER POWER-C 20OZ"
replace product="VITAMIN WATER 20OZ" if item_description=="VITAMINWATER REVIVE 20OZ"
replace product="APPLE AND CHEDDAR" if item_description=="APPLE AND CHEDDAR"
replace product="ENERGY" if item_description=="VITAMINWATER ENERGY"
replace product="CAFFE MOCHA TALL" if item_description=="MOCHA HARVEST NUT TALL"
replace product="ICED CAFFE MOCHA TALL" if item_description=="MOCHA HARVEST NUT ICED TALL"
replace product="PARFAIT PEACHY RASPBERRY" if item_description=="YOGURT PARFAIT PEACH RASP US"
replace product="PARFAIT PEACHY RASPBERRY" if item_description=="YOGURT PARFAIT APPLE CRAN US"
replace product="PARFAIT STRAWBERRY BANANA" if item_description=="YOGURT PARFAIT BANANA STRAW US"
replace product="TEA MISTO SHORT" if item_description=="TEA MISTO SHORT"
replace product="TEA MISTO TALL" if item_description=="TEA MISTO TALL"
replace product="TEA MISTO GRANDE" if item_description=="TEA MISTO GRANDE"
replace product="TEA MISTO VENTI" if item_description=="TEA MISTO VENTI"
replace product="HAZELNUT SIGNATURE HOT CHOCOLATE GRANDE" if item_description=="PRESS 8C SIGNATURE CHROME FY07"
replace product="" if item_description=="PRESS 8CUP DECO FY07"
replace product="" if item_description=="KIT ESPRESSO FY07"
replace product="" if item_description=="KIT ESPRESSO GREEN"
replace product="" if item_description=="DRIPMAKER 10CUP SUGAR WHITE"
replace product="MACAROON COCONUT WITH CHOCOLATE DRIZZLE" if item_description=="COOKIE MACAROON CHOCO DRIZZLED"
replace product="" if item_description=="MUG/SAUCER 13oz RASPBERRY FY07"
replace product="SALAD ASIAN SESAME NOODLE" if item_description=="SALAD ASIAN SESAME NOODLE"
replace product="SALAD BOWTIE PASTA WITH GOAT CHEESE" if item_description=="SALAD BOWTIE PASTA W/ GOAT CHE"
replace product="SALAD TOMATO MOZZARELLA INSALATA" if item_description=="SALAD TOMATO MOZZARELLA INSALATA"
replace product="SALAD FIESTA" if item_description=="SALAD FIESTA"
replace product="SALAD CHICKEN CURRY" if item_description=="SALAD WH CHICKEN CURRY W/ COUS"
replace product="SALAD PASTA CHOP CHOP" if item_description=="SALAD PASTA CHOP CHOP"
replace product="SALAD VEGETABLE VINAIGRETTE" if item_description=="SALAD VEGETABLES & PESTO DIP"
replace product="SCONE RASPBERRY APRICOT THUMBPRINT" if item_description=="SCONE RASP APRICOT THUMBPRINT"
replace product="CINNAMON DOLCE LATTE TALL" if item_description=="LATTE SF CINNAMON DOLCE TALL"
replace product="CINNAMON DOLCE LATTE GRANDE" if item_description=="LATTE SF CINNAMON DOLCE GRANDE"
replace product="FLAVORED SYRUP" if item_description=="SF CINNAMON DOLCE SYRUP"
replace product="LIGHT FLAVORED SYRUP" if item_description=="LIGHT SF CINNAMON DOLCE SYRUP"
replace product="FLAVORED SYRUP" if item_description=="SF CINNAMON DOLCE SYRUP"
replace product="CAKE BANANA NUT LOAF" if item_description=="CAKE LOAF WHOLE BANANA"
replace product="CAKE LEMON LOAF" if item_description=="CAKE LOAF WHOLE LEMON"
replace product="FLAVORED FRAPPUCCINO BLENDED CREME TALL" if item_description=="CINNAMON DOLCE FRAPP CREME TALL"
replace product="FLAVORED FRAPPUCCINO BLENDED CREME GRANDE" if item_description=="CINNAMON DOLCE FRAPP CREME GRANDE"
replace product="FLAVORED FRAPPUCCINO BLENDED CREME VENTI" if item_description=="CINNAMON DOLCE FRAPP CREME"
replace product="TURNOVER APPLE BLOSSOM" if item_description=="TURNOVER APPLE EMPANADA"
replace product="COOKIE ORGANIC OATMEAL" if item_description=="COOKIE ORGANIC OATMEAL"
replace product="ICED TAZO GREEN TEA LATTE GRANDE" if item_description=="BLACK TEA LATTE ICED GRANDE"
replace product="" if item_description=="CHALK BOARD & PENS US/CAN"
replace product="BROWNIE CHOCOLATE CHUNK" if item_description=="BROWNIE CHOCOLATE CHUNK"
replace product="TURNOVER MANGO PINEAPPLE" if item_description=="TURNOVER MANGO PINEAP EMPANADA"
replace product="SANDWICH TURKEY AND JALEPENO HAVARTI" if item_description=="SAND WARM TURKEY & HAVARTI"
replace product="SANDWICH TURKEY & SWISS WITH MAYO" if item_description=="SAND WARM SW TURKEY PEPPERJACK"
replace product="SANDWICH TOMATO MOZARELLA" if item_description=="SAND WARM TOMATO MOZZARELLA"
replace product="" if item_description=="PKG MINI CHOC CHIP COOKIE"
replace product="" if item_description=="PKG MINI BLUEBERRY MUFFIN"
replace product="" if item_description=="COOKIE 2PK BLACK & WHITE"
replace product="COFFEE FRAPPUCCINO BLENDED COFFEE TALL" if item_description=="DULCE DE LECHE FRAP BL COFF TALL"
replace product="COFFEE FRAPPUCCINO LIGHT BLENDED COFFEE VENTI" if item_description=="DULCE DE LECHE LT BL COFFEE VENTI"
replace product="COFFEE FRAPPUCCINO BLENDED COFFEE TALL" if item_description=="DULCE DE LECHE CREME BL COF TALL"
replace product="CAKE LOWFAT ORANGE CREME" if item_description=="COFFEE CAKE RF ORANGE CREME"
replace product="" if item_description=="CUP/SAUCER 12oz PLM RSD LEAF"
replace product="" if item_description=="CUP/SAUCER 10oz PURPLE FLNG L"
replace product="" if item_description=="BOTTLE .05L STAINLESS MILLER"
replace product="" if item_description=="CUP/SAUCER 10oz TEAL FLL/BRZ"
replace product="" if item_description=="CUP/SAUCER 10oz PLUM FLL BRZ"
replace product="" if item_description=="CUP/SAUCER 10oz GRN FALL BRZE"
replace product="" if item_description=="TUMBLR 16oz ART FALL FY07 2IP"
replace product="" if item_description=="CANISTER 56FLoz WHITE FUSION"
replace product="" if item_description=="CUP/SAUCER 10oz GRN FLNG LVS"
replace product="" if item_description=="TEA/COFFEE POT 40OZ FALL BRZ"
replace product="" if item_description=="PLATTER RED PHOTO REAL"
replace product="BREAD MALLORCA SWEET" if item_description=="BREAD MALLORCA SWEET"
replace product="BAR CARMELITA" if item_description=="BAR CARMELITA"
replace product="VITAMIN WATER 20OZ" if item_description=="VITAMINWATER MULTI-V 20OZ"
replace product="ODWALLA POMAGRAND LEMONADE 325ML" if item_description=="ODWALLA POMAGRAND LEMONADE"
replace product="WRAP VEGGIE CRUNCH" if item_description=="SAND VERY VEGGIE CRUNCH WRAP"
replace product="MUFFIN TRIPLE BERRY COBBLER" if item_description=="MUFFIN TRIPLE BERRY COBBLER"
replace product="VANILLA BEAN FRAPPUCCINO BLENDED CREME TALL" if item_description=="VAN BEAN FRAP LT BL CREME TALL"
replace product="VANILLA BEAN FRAPPUCCINO BLENDED CREME GRANDE" if item_description=="VAN BEAN FRAP LT BL CREME GRANDE"
replace product="VANILLA BEAN FRAPPUCCINO BLENDED CREME VENTI" if item_description=="VAN BEAN FRAP LT BL CREME VENTI"
replace product="WHITE CHOCOLATE MOCHA FRAPPUCCINO LIGHT BLENDED COFFEE TALL" if item_description=="WH CHOCO FRAP LT BL CREME TALL"
replace product="WHITE CHOCOLATE MOCHA FRAPPUCCINO LIGHT BLENDED COFFEE GRANDE" if item_description=="WH CHOCO FRAP LT BL CREME GRANDE"
replace product="WHITE CHOCOLATE MOCHA FRAPPUCCINO LIGHT BLENDED COFFEE VENTI" if item_description=="WH CHOCO FRAP LT BL CREME VENTI"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME TALL" if item_description=="CINN DOL FRAP LT BL CREME TALL"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME GRANDE" if item_description=="CINN DOL FRAP LT BL CREME GRANDE"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME VENTI" if item_description=="CINN DOL FRAP LT BL CREME VENTI"
replace product="DOUBLE CHOCOLATY CHIP FRAPPUCCINO LIGHT BLENDED CREME TALL" if item_description=="DB CH CHIP FRAP LT BL CREME TALL"
replace product="DOUBLE CHOCOLATY CHIP FRAPPUCCINO LIGHT BLENDED CREME GRANDE" if item_description=="DB CH CHIP FRAP LT BL CREME GRANDE"
replace product="DOUBLE CHOCOLATY CHIP FRAPPUCCINO LIGHT BLENDED CREME VENTI" if item_description=="DB CH CHIP FRAP LT BL CREME VENTI"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME TALL" if item_description=="STRAW & CR FRAP LT BL CREME TALL"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME GRANDE" if item_description=="STRAW & CR FRAP LT BL CREME GRANDE"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME VENTI" if item_description=="STRAW & CR FRAP LT BL CREME VENTI"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME TALL" if item_description=="TAZO CHAI FRAP LT BL CREME TALL"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME GRANDE" if item_description=="TAZO CHAI FRAP LT BL CREME GRANDE"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME VENTI" if item_description=="TAZO CHAI FRAP LT BL CREME VENTI"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME TALL" if item_description=="GREEN TEA FRAP LT BL CREME TALL"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME GRANDE" if item_description=="GREEN TEA FRAP LT BL CREME GRANDE"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME VENTI" if item_description=="GREEN TEA FRAP LT BL CREME VENTI"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME TALL" if item_description=="SYRUP FRAP LT BL CREME TALL"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME GRANDE" if item_description=="SYRUP FRAP LT BL CREME GRANDE"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME VENTI" if item_description=="SYRUP FRAP LT BL CREME VENTI"
replace product="FLAVORED SYRUP" if item_description=="ORANGE CREME SYRUP"
replace product="FLAVORED SYRUP" if item_description=="ORANGE CREME SYRUP"
replace product="SUGAR FREE FLAVORED SYRUP" if item_description=="SUGAR FREE CARAMEL SYRUP"
replace product="SUGAR FREE FLAVORED SYRUP" if item_description=="SUGAR FREE CARAMEL SYRUP"
replace product="LIGHT FLAVORED SYRUP" if item_description=="LIGHT SUGAR FREE CARAMEL SYRUP"
replace product="CHEDDAR LOWFAT TURKEY BACON CHOLESTEROL-FREE EGG LOWFAT WHITE" if item_description=="FRESNO BKFST RF TURKEY BACON"
replace product="" if item_description=="CREAM & SUGAR 6oz FUSION HOL08"
replace product="" if item_description=="CUP/SAUCER 10oz HOL EXP HOL08"
replace product="" if item_description=="CUP/SAUCER 10oz PNK HOL EXP 08"
replace product="" if item_description=="TBLR 16oz BLU SPRKL RBD HOL08"
replace product="" if item_description=="TBLR 16oz PRPL HANUKKAH HOL08"
replace product="" if item_description=="CUP/PLATE 6oz STRP HOL08"
replace product="SCONE CHEDDAR BROCCOLI SAVORY" if item_description=="SCONE CHEDDAR AND SPINACH"
replace product="SCONE PETITE HERB CHEESE" if item_description=="SCONE PETITE HERB CHEESE INDIV"
replace product="" if item_description=="SCONE PETITE HERB CHEESE 3 PK"
replace product="" if item_description=="CUP/SAUCER 8oz GLS CNDY HOL08"
replace product="COOKIE MINI DAYBREAK WITH NUTS" if item_description=="COOKIE MINI PETITE PALMIERS"
replace product="WRAP THAI TUNA" if item_description=="GARDEN TUNA SALAD WRAP"
replace product="CLUB TURKEY WITH AVACADO" if item_description=="SAND TURKEY CLUB WITH AVOCADO"
replace product="SALAD TERIYAKI WHITE CHICKEN" if item_description=="SALAD TERIYAKI WHITE CHICKEN"
replace product="LIGHT FLAVORED SYRUP" if item_description=="LIGHT JUICY RASPBERRY SYRUP"
replace product="FLAVORED SYRUP" if item_description=="JUICY RASPBERRY SYRUP"
replace product="" if item_description=="PKG MINI DONUT OLD FASHIONED"
replace product="" if item_description=="LIGHT THAI"
replace product="" if item_description=="BEV KIT US PEPPERMINTMOCA CS/2"
replace product="PUMPKIN SPICE FRAPPUCCINO LIGHT BLEMDED CREME TALL" if item_description=="PUMPKIN SP FRAP LT BL CREME TALL"
replace product="PUMPKIN SPICE FRAPPUCCINO LIGHT BLEMDED CREME GRANDE" if item_description=="PUMPKIN SP FRAP LT BL CREME GRANDE"
replace product="PUMPKIN SPICE FRAPPUCCINO LIGHT BLEMDED CREME VENTI" if item_description=="PUMPKIN SP FRAP LT BL CREME VENTI"
replace product="" if item_description=="PRESS 3C COPPER FINSH FY08"
replace product="TAZO DIET" if item_description=="TAZO DIET GIANT PEACH"
replace product="COFFEE CAKE CARAMEL APPLE PECAN" if item_description=="COFFEE CAKE CARML APPLE PECAN"
replace product="CAKE MARBLE LOAF" if item_description=="CAKE LOAF WHOLE MARBLE"
replace product="BAGUETT HAM AND BRIE" if item_description=="SAND WARM HAM AND BRIE BAGUETT"
replace product="" if item_description=="COOKIE RAINBOW 12 PACK"
replace product="TEA SHORT" if item_description=="TEA AWAKE SHORT"
replace product="TEA TALL" if item_description=="TEA AWAKE TALL"
replace product="TEA GRANDE" if item_description=="TEA AWAKE GRANDE"
replace product="TEA VENTI" if item_description=="TEA AWAKE VENTI"
replace product="FILLED CHOCOLATE CHIP SCONE WITH CARAMEL" if item_description=="TEA CALM SHORT"
replace product="TEA TALL" if item_description=="TEA CALM TALL"
replace product="TEA GRANDE" if item_description=="TEA CALM GRANDE"
replace product="TEA VENTI" if item_description=="TEA CALM VENTI"
replace product="TEA SHORT" if item_description=="TEA EARL GREY SHORT"
replace product="TEA TALL" if item_description=="TEA EARL GREY TALL"
replace product="TEA GRANDE" if item_description=="TEA EARL GREY GRANDE"
replace product="TEA VENTI" if item_description=="TEA EARL GREY VENTI"
replace product="TEA SHORT" if item_description=="TEA PASSION SHORT"
replace product="TEA TALL" if item_description=="TEA PASSION TALL"
replace product="TEA GRANDE" if item_description=="TEA PASSION GRANDE"
replace product="TEA VENTI" if item_description=="TEA PASSION VENTI"
replace product="TEA SHORT" if item_description=="TEA REFRESH SHORT"
replace product="TEA TALL" if item_description=="TEA REFRESH TALL"
replace product="TEA GRANDE" if item_description=="TEA REFRESH GRANDE"
replace product="TEA VENTI" if item_description=="TEA REFRESH VENTI"
replace product="VANILLA CREME SHORT" if item_description=="VANILLA CREME KIDS"
replace product="FLAVORED SYRUP" if item_description=="SYRUP CREME KIDS"
replace product="STEAMED APPLE JUICE SHORT" if item_description=="STEAMED APPLE JUICE KIDS"
replace product="FLAVORED CREME SHORT" if item_description=="GINGERBREAD CREME SHORT"
replace product="FLAVORED CREME TALL" if item_description=="GINGERBREAD CREME TALL"
replace product="FLAVORED CREME GRANDE" if item_description=="GINGERBREAD CREME GRANDE"
replace product="FLAVORED CREME VENTI" if item_description=="GINGERBREAD CREME VENTI"
replace product="CAFFE LATTE SHORT" if item_description=="SF GINGERBREAD LATTE SHORT"
replace product="CAFFE LATTE TALL" if item_description=="SF GINGERBREAD LATTE TALL"
replace product="ICED CAFFE LATTE TALL" if item_description=="SF GINGERBREAD LATTE ICED TALL"
replace product="CAFFE LATTE GRANDE" if item_description=="SF GINGERBREAD LATTE GRANDE"
replace product="ICED CAFFE LATTE GRANDE" if item_description=="SF GINGERBREAD LATTE ICED GRANDE"
replace product="CAFFE LATTE VENTI" if item_description=="SF GINGERBREAD LATTE VENTI"
replace product="ICED CAFFE LATTE VENTI" if item_description=="SF GINGERBREAD LATTE ICED VENTI"
replace product="FLAVORED SYRUP" if item_description=="SF GINGERBREAD SYRUP"
replace product="LIGHT SUGAR FREE FLAVORED SYRUP" if item_description=="LT SF GINGERBREAD SYRUP"
replace product="FLAVORED SYRUP" if item_description=="EX SF GINGERBREAD SYRUP"
replace product="" if item_description=="TMBL 16oz BELLA HEARTS WHT 2IP"
replace product="COOKIE COFFEE INFUSED GINGER" if item_description=="COOKIE COFFEE GINGER"
replace product="COOKIE WHITE CHOCOLATE CRANBERRY" if item_description=="COOKIE WHITE CHOCO PECAN SNICK"
replace product="" if item_description=="ON DEMAND CORE PROMO TALL"
replace product="" if item_description=="ON DEMAND CLOVER MONTH TALL"
replace product="" if item_description=="ON DEMAND CLOVER MONTH GRANDE"
replace product="" if item_description=="VARIETY MINI PACK #1"
replace product="" if item_description=="VARIETY MINI PACK #2"
replace product="WRAP BACON AVOCADO AGED CHEDDAR & EGG" if item_description=="BREAKFAST BACON AVOCADO WRAP"
replace product="WRAP BREAKFAST SPINACH" if item_description=="BREAKFAST SPINACH WRAP"
replace product="JUICE ODWALLA PUMPKIN 450ML" if item_description=="JUICE ODWALLA PUMPKIN 450ML"
replace product="DOUGHNUT OLD FASHIONED" if item_description=="DOUGHNUT OLD FASHION ROUND"
replace product="" if item_description=="CUP/SAUCER WHT URBAN DMI FY08"
replace product="CAKE LOWFAT PUMPKIN CHOCOLATE CHIP COFFEE" if item_description=="COFFEE CAKE RF PUMPKIN CHOC CH"
replace product="SQUARE COCOA CRISPY" if item_description=="BAR COCOA CRISPY"
replace product="SCONE CRAN-APPLE CRUMB" if item_description=="SCONE APPLE CRANBERRY CRUMB"
replace product="LOAF BANANA NUT" if item_description=="WHOLE LOAF BANANA NUT"
replace product="" if item_description=="PKG MINI BLUEBERRY SCONE"
replace product="SCONE CARAMEL FILLED" if item_description=="SCONE CARAMEL FILLED"
replace product="SYRUP FLAVORED LATTE TALL" if item_description=="SHORTBREAD LATTE TALL"
replace product="SYRUP FLAVORED LATTE GRANDE" if item_description=="SHORTBREAD LATTE GRANDE"
replace product="FLAVORED SYRUP" if item_description=="SHORTBREAD SYRUP"
replace product="SALAD PESTO PASTA" if item_description=="SALAD PESTO PASTA"
replace product="" if item_description=="TMBL 12oz PNK DIANA SPR08 2IP"
replace product="" if item_description=="TMBL 12oz GRN DIANA SPRING 08"
replace product="PEPPERMINT WHITE CHOCOLATE MOCHA SHORT" if item_description=="PEPPERMINT WH CHOCO MOCHA SHORT"
replace product="PEPPERMINT WHITE CHOCOLATE MOCHA TALL" if item_description=="PEPPERMINT WH CHOCO MOCHA TALL"
replace product="ICED PEPPERMINT WHITE CHOCOLATE MOCHA TALL" if item_description=="PEPPERMINT WH CHOCO MOC ICD TALL"
replace product="PEPPERMINT WHITE CHOCOLATE MOCHA GRANDE" if item_description=="PEPPERMINT WH CHOCO MOCHA GRANDE"
replace product="ICED PEPPERMINT WHITE CHOCOLATE MOCHA GRANDE" if item_description=="PEPPERMINT WH CHOCO MOC ICD GRANDE"
replace product="PEPPERMINT WHITE CHOCOLATE MOCHA VENTI" if item_description=="PEPPERMINT WH CHOCO MOCHA VENTI"
replace product="ICED PEPPERMINT WHITE CHOCOLATE MOCHA VENTI" if item_description=="PEPPERMINT WH CHOCO MOC ICD VENTI"
replace product="PEPPERMINT HOT CHOCOLATE SHORT" if item_description=="PEPPERMINT WH HOT CHOCO KIDS"
replace product="PEPPERMINT HOT CHOCOLATE SHORT" if item_description=="PEPPERMINT WH HOT CHOCO SHORT"
replace product="PEPPERMINT HOT CHOCOLATE TALL" if item_description=="PEPPERMINT WH HOT CHOCO TALL"
replace product="PEPPERMINT HOT CHOCOLATE GRANDE" if item_description=="PEPPERMINT WH HOT CHOCO GRANDE"
replace product="PEPPERMINT HOT CHOCOLATE VENTI" if item_description=="PEPPERMINT WH HOT CHOCO VENTI"
replace product="PEPPERMINT MOCHA FRAPPUCCINO BLENDED COFFEE TALL" if item_description=="PEP-MINT WH CH MOC FRAPP TALL"
replace product="PEPPERMINT MOCHA FRAPPUCCINO BLENDED COFFEE GRANDE" if item_description=="PEP-MINT WH CH MOC FRAPP GRANDE"
replace product="PEPPERMINT MOCHA FRAPPUCCINO BLENDED COFFEE VENTI" if item_description=="PEP-MINT WH CH MOC FRAPP VENTI"
replace product="PEPPERMINT MOCHA FRAPPUCCINO LIGHT BLENDED COFFEE TALL" if item_description=="PEP-MINT WH CH MOC LT FRAPP TALL"
replace product="PEPPERMINT MOCHA FRAPPUCCINO LIGHT BLENDED COFFEE GRANDE" if item_description=="PEP-MINT WH CH MOC LT FRAPP GRANDE"
replace product="PEPPERMINT MOCHA FRAPPUCCINO LIGHT BLENDED COFFEE VENTI" if item_description=="PEP-MINT WH CH MOC LT FRAPP VENTI"
replace product="PEPPERMINT MOCHA FRAPPUCCINO BLENDED CREME TALL" if item_description=="PEP-MINT WH CH MOC CRMFR TALL"
replace product="PEPPERMINT MOCHA FRAPPUCCINO BLENDED CREME GRANDE" if item_description=="PEP-MINT WH CH MOC CRMFR GRANDE"
replace product="PEPPERMINT MOCHA FRAPPUCCINO BLENDED CREME VENTI" if item_description=="PEP-MINT WH CH MOC CRMFR VENTI"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME TALL" if item_description=="PEP-MINT WH CH MOC LT CRMFR TALL"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME GRANDE" if item_description=="PEP-MINT WH CH MOC LT CRMFR GRANDE"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME VENTI" if item_description=="PEP-MINT WH CH MOC LT CRMFR VENTI"
replace product="FLAVORED CREME SHORT" if item_description=="GINGERBREAD CREME KIDS"
replace product="PUMPKIN SPICE CREME SHORT" if item_description=="PUMPKIN SPICE CREME KIDS"
replace product="PEPPERMINT CHOCOLATE FRAPPUCCINO BLENDED CREME TALL" if item_description=="PEPP CHOCO FRAPP BL CREME TALL"
replace product="PEPPERMINT CHOCOLATE FRAPPUCCINO BLENDED CREME GRANDE" if item_description=="PEPP CHOCO FRAPP BL CREME GRANDE"
replace product="PEPPERMINT CHOCOLATE FRAPPUCCINO BLENDED CREME VENTI" if item_description=="PEPP CHOCO FRAPP BL CREME VENTI"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME GRANDE" if item_description=="PEPP CHOCO FRAPP LT BL CR GRANDE"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME VENTI" if item_description=="PEPP CHOCO FRAPP LT BL CR VENTI"
replace product="COOKIE GINGERBREAD MITTEN" if item_description=="COOKIE GINGERBREAD MAN"
replace product="CAFFE VANILLA FRAPPUCCINO BLENDED COFFEE GRANDE" if item_description=="BOTTLE 20oz CLEAR COFFEHOUSE"
replace product="BROWNIE SNOWCAP" if item_description=="BAR BROWNIE MARSHMELLOW SNOWCP"
replace product="CAKE CUPCAKE VANILLA" if item_description=="CAKE CUPCAKE VANILLA"
replace product="CAKE STICKY TOFFEE COFFEE WITH PECANS" if item_description=="CAKE TOFFEE COFFEE"
replace product="MUFFIN OAT NUT" if item_description=="MUFFIN OAT NUT"
replace product="JUICE ODWALLA ANTIOXIDANCE 450ML" if item_description=="JUICE ODWALLA ANTIOXIDANCE 450"
replace product="COFFEE DRIP" if item_description=="DUMMY SKU DRIP"
replace product="ESPRESSO SHOT" if item_description=="DUMMY SKU ESPRESSO"
replace product="" if item_description=="DUMMY SKU PASTRY"
replace product="" if item_description=="DUMMY SKU BLENDED BEVERAGE"
replace product="" if item_description=="MISC SALES POS RETAIL"
replace product="CAKE LOWFAT CHERRY LEMON COFFEE WITH OATMEAL-PECAN STREUSEL" if item_description=="CAKE RF CHERRY LEMON COFFEE"
replace product="COFFEE TALL" if item_description=="ON DEMAND COFFEE PRESS TALL"
replace product="ON DEMAND CLOVER SPECIAL GRANDE" if item_description=="ON DEMAND CLOVER SPECIAL GRANDE"
replace product="BRUSCHETTA LOW FAT CHICKEN" if item_description=="SANDWICH LOW FAT CHICKN BRUSCH"
replace product="" if item_description=="CUP/SAUCER 11oz WHITE"
replace product="" if item_description=="FRAME PHOTO MAGNETIC"
replace product="SYRUP FLAVORED LATTE SHORT" if item_description=="LATTE HONEY SHORT"
replace product="SYRUP FLAVORED LATTE TALL" if item_description=="LATTE HONEY TALL"
replace product="ICED SYRUP FLAVORED LATTE TALL" if item_description=="LATTE HONEY ICED TALL"
replace product="SYRUP FLAVORED LATTE GRANDE" if item_description=="LATTE HONEY GRANDE"
replace product="ICED SYRUP FLAVORED LATTE GRANDE" if item_description=="LATTE HONEY ICED GRANDE"
replace product="SYRUP FLAVORED LATTE VENTI" if item_description=="LATTE HONEY VENTI"
replace product="ICED SYRUP FLAVORED LATTE VENTI" if item_description=="LATTE HONEY ICED VENTI"
replace product="FLAVORED CREME SHORT" if item_description=="HONEY CREME KIDS"
replace product="FLAVORED CREME SHORT" if item_description=="HONEY CREME SHORT"
replace product="FLAVORED CREME TALL" if item_description=="HONEY CREME TALL"
replace product="FLAVORED CREME GRANDE" if item_description=="HONEY CREME GRANDE"
replace product="FLAVORED CREME VENTI" if item_description=="HONEY CREME VENTI"
replace product="FLAVORED SYRUP" if item_description=="HONEY SYRUP"
replace product="LIGHT FLAVORED SYRUP" if item_description=="LT HONEY SYRUP"
replace product="FLAVORED SYRUP" if item_description=="EX HONEY SYRUP"
replace product="HONEY DRIZZLE" if item_description=="HONEY DRIZZLE"
replace product="FLAVORED FRAPPUCCINO BLENDED COFFEE TALL" if item_description=="HONEY FRAPPUCCINO TALL"
replace product="FLAVORED FRAPPUCCINO BLENDED COFFEE GRANDE" if item_description=="HONEY FRAPPUCCINO GRANDE"
replace product="FLAVORED FRAPPUCCINO BLENDED COFFEE VENTI" if item_description=="HONEY FRAPPUCCINO VENTI"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED COFFEE TALL" if item_description=="HONEY FRAPPUCCINO LIGHT TALL"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED COFFEE GRANDE" if item_description=="HONEY FRAPPUCCINO LIGHT GRANDE"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED COFFEE VENTI" if item_description=="HONEY FRAPPUCCINO LIGHT VENTI"
replace product="FLAVORED FRAPPUCCINO BLENDED CREME TALL" if item_description=="HONEY FRAPP CREME TALL"
replace product="FLAVORED FRAPPUCCINO BLENDED CREME GRANDE" if item_description=="HONEY FRAPP BL CREME GRANDE"
replace product="FLAVORED FRAPPUCCINO BLENDED CREME VENTI" if item_description=="HONEY FRAPP CREME VENTI"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME TALL" if item_description=="HONEY FRAPP LT CREME TALL"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME GRANDE" if item_description=="HONEY FRAPP LT CREME GRANDE"
replace product="FLAVORED FRAPPUCCINO LIGHT BLENDED CREME VENTI" if item_description=="HONEY FRAPP LT CREME VENTI"
replace product="DOUGHNUT TOP POT CHOCOLATE SANDCASTLE" if item_description=="DOUGHNUT CHOCOLATE SANDCASTLE"
replace product="CAFFE LATTE SHORT" if item_description=="LATTE SKINNY CDL SHORT"
replace product="SKINNY LATTE TALL" if item_description=="LATTE SKINNY CDL TALL"
replace product="ICED SKINNY LATTE TALL" if item_description=="LATTE SKINNY CDL TALL ICED"
replace product="SKINNY LATTE GRANDE" if item_description=="LATTE SKINNY CDL GRANE"
replace product="ICED SKINNY LATTE GRANDE" if item_description=="LATTE SKINNY CDL ICED GRANDE"
replace product="SKINNY LATTE VENTI" if item_description=="LATTE SKINNY CDL VENTI"
replace product="ICED SKINNY LATTE VENTI" if item_description=="LATTE SKINNY CDL ICED VENTI"
replace product="SKINNY MOCHA SHORT" if item_description=="SKINNY MOCHA SHORT"
replace product="SKINNY MOCHA TALL" if item_description=="SKINNY MOCHA TALL"
replace product="ICED SKINNY MOCHA TALL" if item_description=="SKINNY MOCHA ICED TALL"
replace product="SKINNY MOCHA GRANDE" if item_description=="SKINNY MOCHA GRANDE"
replace product="ICED SKINNY MOCHA GRANDE" if item_description=="SKINNY MOCHA ICED GRANDE"
replace product="SKINNY MOCHA VENTI" if item_description=="SKINNY MOCHA VENTI"
replace product="ICED SKINNY MOCHA VENTI" if item_description=="SKINNY MOCHA ICED VENTI"
replace product="FLAVORED SYRUP" if item_description=="SF MOCHA SYRUP"
replace product="SUGAR FREE FLAVORED SYRUP" if item_description=="EX SF MOCHA SYRUP"
replace product="LIGHT SUGAR FREE FLAVORED SYRUP" if item_description=="LIGHT SF MOCHA SYRUP"
replace product="" if item_description=="COOKIE CHOCOLATE MADELEINE 3PK"
replace product="CAKE CLASSIC COFFEE" if item_description=="CAKE STARBUCKS CLASSIC COFFEE"
replace product="BANANA CHOCOLATE BLEND GRANDE" if item_description=="BANANA CHOCO BLEND GRANDE"
replace product="CITRUS MANGO BLEND GRANDE" if item_description=="CITRUS MANGO BLEND GRANDE"
replace product="PROTEIN FIBER POWDER" if item_description=="PROTEIN POWDER"
replace product="BANANA" if item_description=="BANANA"
replace product="SKINNY HAZELNUT LATTE GRANDE" if item_description=="SKINNY HAZEL LATTE SHORT"
replace product="SKINNY HAZELNUT LATTE TALL" if item_description=="SKINNY HAZEL LATTE TALL"
replace product="ICED SKINNY HAZELNUT LATTE TALL" if item_description=="SKINNY HAZEL LATTE ICED TALL"
replace product="SKINNY HAZELNUT LATTE GRANDE" if item_description=="SKINNY HAZEL LATTE GRANDE"
replace product="ICED SKINNY HAZELNUT LATTE GRANDE" if item_description=="SKINNY HAZEL ICED LATTE GRANDE"
replace product="SKINNY HAZELNUT LATTE VENTI" if item_description=="SKINNY HAZEL LATTE VENTI"
replace product="ICED SKINNY HAZELNUT LATTE VENTI" if item_description=="SKINNY HAZ ICED LATTE VENTI"
replace product="SKINNY VANILLA LATTE SHORT" if item_description=="SKINNY VAN LATTE SHORT"
replace product="SKINNY VANILLA LATTE TALL" if item_description=="SKINNY VAN LATTE TALL"
replace product="ICED SKINNY VANILLA LATTE TALL" if item_description=="SKINNY VANILLA ICED LATTE TALL"
replace product="SKINNY VANILLA LATTE GRANDE" if item_description=="SKINNY VANILLA LATTE GRANDE"
replace product="ICED SKINNY VANILLA LATTE GRANDE" if item_description=="SKINNY VAN ICED LATTE GRANDE"
replace product="SKINNY VANILLA LATTE VENTI" if item_description=="SKINNY VANILLA LATTE VENTI"
replace product="ICED SKINNY VANILLA LATTE VENTI" if item_description=="SKINNY VAN ICED LATTE VENTI"
replace product="SKINNY CARAMEL LATTE SHORT" if item_description=="SKINNY CARAMEL LATTE SHORT"
replace product="SKINNY CARAMEL LATTE TALL" if item_description=="SKINNY CARMEL LATTE TALL"
replace product="ICED SKINNY CARAMEL LATTE TALL" if item_description=="SKINNY CARMEL ICED TALL"
replace product="SKINNY CARAMEL LATTE GRANDE" if item_description=="SKINNY CARAMEL LATTE GT"
replace product="ICED SKINNY CARAMEL LATTE GRANDE" if item_description=="SKINNY CARAMEL ICED LATTE GRANDE"
replace product="SKINNY CARAMEL LATTE VENTI" if item_description=="SKINNY CARAMEL LATTE VENTI"
replace product="ICED SKINNY CARAMEL LATTE VENTI" if item_description=="SKINNY CARAMEL ICED LATTE VENTI"
replace product="JUICE NAKED ORANGE 10OZ" if item_description=="JUICE 10oz NAKED ORANGE"
replace product="JUICE NAKED ORANGE 15.2OZ" if item_description=="JUICE 15.2oz NAKED OJ"
replace product="JUICE NAKED MIGHTY MANGO 10OZ" if item_description=="JUICE 10oz NAKED MIGHTY MANGO"
replace product="JUICE PROTEIN ZONE 10OZ" if item_description=="JUICE 10oz NAKED PROTEIN ZONE"
replace product="SWEET TEA TALL" if item_description=="SWEET TEA TALL"
replace product="SWEET TEA GRANDE" if item_description=="SWEET TEA GRANDE"
replace product="SWEET TEA VENTI" if item_description=="SWEET TEA VENTI"
replace product="SWEET TEA LEMONADE TALL" if item_description=="SWEET TEA LEMONADE TALL"
replace product="SWEET TEA LEMONADE GRANDE" if item_description=="SWEET TEA LEMONADE GRANDE"
replace product="SWEET TEA LEMONADE VENTI" if item_description=="SWEET TEA LEMONADE VENTI"
replace product="DOUGHNUT VANILLA CARAMEL" if item_description=="DONUT VANILLA CARAMEL"
replace product="COOKIE OATMEAL CRANBERRY" if item_description=="COOKIE OATMEAL CRANBERRY"
replace product="MUFFIN LOWFAT CRANBERRY APPLE" if item_description=="MUFFIN REDUCED FAT CRAN APPLE"
replace product="MUFFIN LOWFAT POMEAGRANITE" if item_description=="MUFFIN REDUCED FAT POMEAGRANTE"
replace product="MUFFIN LOWFAT HIGH FIBER BRAN" if item_description=="MUFFIN LOWFAT HIGH FIBER BRAN"
replace product="COFFEE SHORT" if item_description=="ON DEMAND COFFEE # 8 short"
replace product="" if item_description=="PKG MINI BAGEL PLAIN"
replace product="" if item_description=="PK MINI BAGEL MULTIGRAIN"
replace product="" if item_description=="PKG MINI RASPBERRY SCONE"
replace product="BAR PECAN" if item_description=="BAR PECAN MAGIC"
replace product="CARAMEL FRAPPUCCINO BLENDED COFFEE TALL" if item_description=="CARAMEL ESPRESSO FRAPP TALL"
replace product="CARAMEL FRAPPUCCINO BLENDED COFFEE GRANDE" if item_description=="CARAMEL ESPRESSO FRAPP GRANDE"
replace product="CARAMEL FRAPPUCCINO BLENDED COFFEE VENTI" if item_description=="CARAMEL ESPRESSO FRAPP VENTI"
replace product="SKINNY LATTE SHORT" if item_description=="SKINNY LATTE SHORT"
replace product="SKINNY LATTE TALL" if item_description=="SKINNY LATTE TALL"
replace product="ICED SKINNY LATTE TALL" if item_description=="SKINNY LATTE ICED TALL"
replace product="SKINNY LATTE GRANDE" if item_description=="SKINNY LATTE GRANDE"
replace product="ICED SKINNY LATTE GRANDE" if item_description=="SKINNY LATTE ICED GRANDE"
replace product="SKINNY LATTE VENTI" if item_description=="SKINNY LATTE VENTI"
replace product="ICED SKINNY LATTE VENTI" if item_description=="SKINNY ICED LATTE VENTI"
replace product="COFFEE SHORT" if item_description=="DED PIKE PLACE ROAST 8OZ"
replace product="COFFEE 40Z" if item_description=="DED PIKE PLACE ROAST 4OZ"
replace product="LEMONADE BLENDED BEVERAGE TALL" if item_description=="BLENDED LEMONADE TALL"
replace product="LEMONADE BLENDED BEVERAGE GRANDE" if item_description=="BLENDED LEMONADE GRANDE"
replace product="LEMONADE BLENDED BEVERAGE VENTI" if item_description=="BLENDED LEMONADE VENTI"
replace product="LEMONADE BLENDED BEVERAGE WITH TAZO ZEN GREEN TEA TALL" if item_description=="BLENDED LEMONADE W/TEA TALL"
replace product="LEMONADE BLENDED BEVERAGE WITH TAZO ZEN GREEN TEA GRANDE" if item_description=="BLENDED LEMONADE TEA GRANDE"
replace product="LEMONADE BLENDED BEVERAGE WITH TAZO ZEN GREEN TEA VENTI" if item_description=="BLENDED LEMONADE W/TEA VENTI"
replace product="STARBUCKS DOUBLESHOT ON ICE BEVERAGE GRANDE" if item_description=="DOUBLESHOT ON ICE TALL"
replace product="STARBUCKS DOUBLESHOT ON ICE BEVERAGE GRANDE" if item_description=="DOUBLESHOT ON ICE GRANDE"
replace product="STARBUCKS DOUBLESHOT ON ICE BEVERAGE GRANDE" if item_description=="DOUBLESHOT ON ICE VENTI"
replace product="CARAMEL FRAPPUCCINO LIGHT BLENDED COFFEE TALL" if item_description=="FRAPP TALL LT CARAMEL ESPRESSO"
replace product="CARAMEL FRAPPUCCINO LIGHT BLENDED COFFEE GRANDE" if item_description=="FRAPP GRANDE LT CARAMEL ESPRESSO"
replace product="CARAMEL FRAPPUCCINO LIGHT BLENDED COFFEE VENTI" if item_description=="FRAPP VENTI LT CARAMEL ESPRESSO"
replace product="CAKE LOWFAT STRAWBERRY & CREME" if item_description=="CCAKE RF STRAWBERRY & CREME"
replace product="SCONE LEMON POPPYSEED" if item_description=="SCONE LEMON POPPYSEED"
replace product="SCONE PECAN DATE" if item_description=="SCONE PECAN DATE"
replace product="SCONE POLENTA CHERRY" if item_description=="SCONE POLENTA CHERRY"
replace product="SCONE VEGAN FRUIT" if item_description=="SCONE ORGANIC VEGAN FRUIT"
replace product="FRUIT STRAWBERRY KIWI MANGO" if item_description=="FRUIT STRAWBERRY KIWI MANGO"
replace product="ENERGY" if item_description=="ENERGY"
replace product="COOKIE TOFFEE PECAN" if item_description=="COOKIE TOFFEE PECAN"
replace product="STELLA BAKED BERRY" if item_description=="STELLA BERRY"
replace product="CAFFE VANILLA FRAPPUCCINO BLENDED COFFEE VENTI" if item_description=="DBLSHOT ENERGY+COFFEE VAN 150Z"
replace product="STARBUCKS DOUBLESHOT ON ICE +ENERGY BEVERAGE GRANDE" if item_description=="DBLSHOT ENRGY+COFFE MOCHA 15OZ"
replace product="" if item_description=="TBLR 12oz BLU FLN FLWRS IP/2"
replace product="" if item_description=="PRESS COFFEE 8C BLK KENYA FY08"
replace product="JUICE NAKED WATERMELON 15.2OZ" if item_description=="JUICE 15.2oz NAKED WATERMELON"
replace product="JUICE NAKED PEACH MANGO 15.2OZ" if item_description=="JUICE 15.2oz NAKED PEACH MANGO"
replace product="JUICE NAKED PROTEIN ZONE 15.2OZ" if item_description=="JUICE 15.2oz NAKED PROTEIN ZON"
replace product="ICED CAPPUCCINO TALL" if item_description=="CAPPUCCINO ICED TALL"
replace product="ICED CAPPUCCINO GRANDE" if item_description=="CAPPUCCINO ICED GRANDE"
replace product="ICED CAPPUCCINO VENTI" if item_description=="CAPPUCCINO ICED VENTI"
replace product="LEMONADE BLENDED BEVERAGE GRANDE" if item_description=="BLENDED ALTERNATIVE GRANDE"
replace product="" if item_description=="$2 GRANDE"
replace product="ICED COFFEE TALL" if item_description=="ON DEMAND COFFEE PRESS ICED TALL"
replace product="ICED COFFEE GRANDE" if item_description=="ON DEMAND COFFEE PRESS ICED GRANDE"
replace product="COFFEE TALL" if item_description=="REFILL TALL"
replace product="ICED COFFEE GRANDE" if item_description=="ICED REFILL GRANDE"
replace product="ICED COFFEE VENTI" if item_description=="ICED REFILL 24OZ"
replace product="FLAVORED SYRUP" if item_description=="SHOT DARK CHERRY SYRUP"



ge consume=1
replace consume=0 if product==""

rename product name
sort name

* Drop sandwhiches and salads:

*drop if strpos(name,"SANDWHICH")~=0
*drop if strpos(name,"BRUSCHETTA")~=0
*drop if strpos(name,"WRAP")~=0
*drop if strpos(name,"BAGUETT")~=0
*drop if strpos(name,"BREAKFAST")~=0
*drop if strpos(name,"SALAD")~=0

save ../data/working/productfile_consumption_ids_calorienames, replace

* Generate file with all zones

ge zone=5
save ../data/working/productfile_consumption_ids_calorienames_zone5, replace
clear
use ../data/working/productfile_consumption_ids_calorienames
ge zone=15
save ../data/working/productfile_consumption_ids_calorienames_zone15, replace
clear
use ../data/working/productfile_consumption_ids_calorienames
ge zone=16
save ../data/working/productfile_consumption_ids_calorienames_zone16, replace
clear
use ../data/working/productfile_consumption_ids_calorienames
ge zone=51
save ../data/working/productfile_consumption_ids_calorienames_zone51, replace
clear
use ../data/working/productfile_consumption_ids_calorienames
ge zone=64
save ../data/working/productfile_consumption_ids_calorienames_zone64, replace
clear
use ../data/working/productfile_consumption_ids_calorienames
ge zone=0

clear
use ../data/working/productfile_consumption_ids_calorienames_zone5
append using ../data/working/productfile_consumption_ids_calorienames_zone15
append using ../data/working/productfile_consumption_ids_calorienames_zone16
append using ../data/working/productfile_consumption_ids_calorienames_zone51
append using ../data/working/productfile_consumption_ids_calorienames_zone64

sort name zone
save ../data/working/productfile_consumption_ids_calorienames_zones, replace







